### ISSUE TITLE
Crash after a few hours

### ISSUE THREAD

**Issue by hangim** [skilion/onedrive#425] opened 2018-10-13 07:40 UTC
**version**: `onedrive v1.1.3`

Hey, when I run `onedrive` from command by manual,  I always found it will crash after a few hours. And the time is random. After the crash, I restart it, everything come back to OK.

I think it may be caused by the **network problem**, software exit after connecting abort.

I know I can use `Systemd` or something else to restart it when crash, but I don't think it's a good practice.

So I hope it can add some arguments, like `retry=always`, to avoid the software exit frequently.

**Comment by abraunegg** [comment] 2018-10-13 08:05
Can you edit the service files to run in verbose mode, post the results to assist.

Also, the 'skilion' codebase contains several defects which have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need to clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by hangim** [comment] 2018-10-13 08:30
After restarted, upload resume.
```
xxx@xxx:~$ onedrive -m -v
Loading config ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /data/OneDrive
Initializing the Synchronization Engine ...
Trying to restore the upload session ...
Continuing the upload session ...
Uploading fragment: 1751121920-1761607680/7700161916
Uploading fragment: 1761607680-1772093440/7700161916
Uploading fragment: 1772093440-1782579200/7700161916
..................................
...[Omit redundant information]...
..................................
```

**Comment by abraunegg** [comment] 2018-10-13 08:51
So when running manually - there is no segfault or crash? It just stops and you have to restart it?

**Comment by hangim** [comment] 2018-10-13 08:55
Seems like it. Stopped for no reason.

**Comment by wtdcode** [comment] 2018-11-04 10:16
Just edit /usr/lib/systemd/user/onedrive.service and change
```
Restart=no
```
to
```
Restart=always
```
Perhaps this way is ollowing the UNIX philosophy?

**Comment by hangim** [comment] 2018-11-04 11:32
> Just edit /usr/lib/systemd/user/onedrive.service and change
> 
> ```
> Restart=no
> ```
> to
> 
> ```
> Restart=always
> ```
> Perhaps this way is **following the UNIX philosophy**?

 I know `systemd` is always fine for a long time running.

But, I just **feel strange and uncomfortable**, when I manually start it from the terminal.

My scene is, I want to upload all file once and just once, and I don't care sync because of no need.

So I don't want to use `systemd`, manually start and stop is enough.

**Comment by wtdcode** [comment] 2018-11-04 11:39
I am not sure the design is intentional or not, but it should correspond to the philosophy `Do one thing and do it well` since you can use `systemd` or something else to meet your needs.

**Comment by abraunegg** [comment] 2018-11-04 21:03
> My scene is, I want to upload all file once and just once, and I don't care sync because of no need.

I would not use monitor mode then - do not use the `-m` flag. Then you may get an idea as to why the application is crashing as the crash / debug will be written out.

**Comment by wtdcode** [comment] 2018-11-05 12:19
@abraunegg
Due to some reason, I guess it just crashes because of timeout for too many times, as I have encountered before.

**Comment by abraunegg** [comment] 2019-11-26 20:43
@wtdcode 
This issue most likely was caused by error codes not being caught when doing session fragment uploads.

This is now 100% fixed via https://github.com/abraunegg/onedrive/pull/721

**Comment by wtdcode** [comment] 2019-11-27 01:20
@abraunegg
Sounds great!

**Comment by druonysus** [comment] 2019-11-27 01:53
I have told systemd to restart the service but it crashes every 20 seconds or so. Very annoying.

**Comment by abraunegg** [comment] 2019-11-27 01:54
@druonysus 
If you are using the 'skillion' codebase .. to be expected.

What does `onedrive --version` say for your version?

**Closed** 2020-10-27 16:39 UTC
