### ISSUE TITLE
Unknown item id seg fault

### ISSUE THREAD

**Issue by ChrisLane** [skilion/onedrive#141] opened 2017-01-11 13:37 UTC
I'm currently running the version from commit 203062f and just had this error: http://paste2.org/9ackNId4

Line 9 onwards now occurs every time I attempt to run the onedrive client.

**Comment by hugomilan** [comment] 2017-01-11 19:52
I'm having the same issue. I found out that every time this error happens, I have to do an "onedrive --resync". After it resyncs, it works nice for a while (less than 5 min in "onedrive -monitor") when suddenly it throws this error. I thought it might be related to some files that I'm changing constantly (so the software, Calibre, was creating temporally files that were faster deleted), then I ignored these files but the error persists.

Ideas?

**Comment by hugomilan** [comment] 2017-01-12 00:14
I run the onedrive again with 'onedrive --verbose'. The important output is:
4F8AB83334481152!77028 Hugo F.M. Milan
The item is marked for deletion
4F8AB83334481152!77029 Tetrahedral node for Transmission-Line Modeling (TLM) applied to Bio-heat Transfer (375)
Then the error apears.

The folder 'Hugo F.M. Milan' is already deleted in OneDrive online and in my files (I think, 90% sure; couldn't confirm because I kept the testing as you can see). Then, it goes to the next item, which was inside the folder 'Hugo F.M. Milan'.

I went to OneDrive online and restored the folder 'Hugo F.M. Milan'. Then I did 'onedrive --verbose'. After that I could see the folder in my files and the onedrive run just fine. I, finally, delete the folder in my files and run 'onedrive'. I could confirm that the folder was deleted both, in my files and online.

I suspect that onedrive is trying to delete a file that it doesn't find online, and that would explain the 'Unknow item id'. Maybe, onedrive should verify if the item exists online before sending command to delete (if such thing wasn't implemented yet and is possible).

**Comment by joecool1029** [comment] 2017-01-14 22:29
See #138 .

**Comment by thiagocrepaldi** [comment] 2017-01-20 16:24
I can reproduce this crash in two ways. In both cases, DURING the FIRST sync, if I remove one item or rename it, sync will crash with "Unknow item id" (there is a typo in the message too).

That seems to happen because item's db refers to the old item reference, but the cloud reference already does not exist or point to the new name. item.d:237 is an "enforce" call that will throw an exception

**Comment by skilion** [comment] 2017-03-11 13:25
Should be fixed with 957b034805985d40a25d8521996791c74c055a64

**Closed by skilion** 2017-03-11 13:25 UTC

**Comment by obrobertsen** [comment] 2017-06-15 16:40
**I have the same today, just compiled latest version today, here are the logfile:**
juni 15 18:27:01 mylaptop systemd[2061]: Started OneDrive Free Client.
juni 15 18:27:32 mylaptop onedrive[3406]: Moving remote item: ./file1.txt -> ./rename this file1.txt
juni 15 18:27:58 mylaptop onedrive[3406]: Uploading: ./hello.txt
juni 15 18:32:30 mylaptop onedrive[3406]: Deleting remote item: ./hello.txt
juni 15 18:33:05 mylaptop onedrive[3406]: object.Exception@src/itemdb.d(231): **Unknow item id**
juni 15 18:33:05 mylaptop onedrive[3406]: ----------------
juni 15 18:33:05 mylaptop onedrive[3406]: /usr/include/dmd/phobos/std/exception.d:388 pure @safe bool std.exception.enforce!(Except
juni 15 18:33:05 mylaptop onedrive[3406]: src/itemdb.d:231 immutable(char)[] itemdb.ItemDatabase.computePath(const(char)[], const(c
juni 15 18:33:05 mylaptop onedrive[3406]: src/sync.d:361 void sync.SyncEngine.deleteItems() [0x5db2cb]
juni 15 18:33:05 mylaptop onedrive[3406]: src/sync.d:185 void sync.SyncEngine.applyDifferences() [0x5d9ac7]
juni 15 18:33:05 mylaptop systemd[2061]: onedrive.service: Main process exited, code=killed, status=11/SEGV
juni 15 18:33:05 mylaptop systemd[2061]: onedrive.service: Unit entered failed state.
juni 15 18:33:05 mylaptop systemd[2061]: onedrive.service: Failed with result 'signal'.
