### ISSUE TITLE
HTTP request returned status code 400 (Bad Request)

### ISSUE THREAD

**Issue by barghest** [skilion/onedrive#156] opened 2017-02-28 21:07 UTC
Hi,
when onedrive tries to upload files I get the error message:

```
sync.SyncException@src/sync.d(348): HTTP request returned status code 400 (Bad Request)
{
    "error": {
        "code": "invalidRequest",
        "message": "Bad Argument"
    }
}
----------------
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x5c939c]
??:? void main.performSync(sync.SyncEngine) [0x5b6860]
??:? _Dmain [0x5b6022]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5dd336]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5dd27c]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5dd2f2]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5dd27c]
??:? _d_run_main [0x5dd1f6]
??:? main [0x5b9857]
??:? __libc_start_main [0x7bebb290]
onedrive.OneDriveException@src/onedrive.d(382): HTTP request returned status code 400 (Bad Request)
{
    "error": {
        "code": "invalidRequest",
        "message": "Bad Argument"
    }
}
----------------
??:? std.json.JSONValue onedrive.OneDriveApi.upload(immutable(char)[], immutable(char)[]) [0x5bf33f]
??:? void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x5cbd97]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5cb6a2]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5cb47d]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5cb47d]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5cb47d]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5cb47d]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5cb47d]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x5c928b]
??:? void main.performSync(sync.SyncEngine) [0x5b6860]
??:? _Dmain [0x5b6022]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5dd336]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5dd27c]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5dd2f2]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5dd27c]
??:? _d_run_main [0x5dd1f6]
??:? main [0x5b9857]
??:? __libc_start_main [0x7bebb290]
Segmentation fault (core dumped)

```
I already tried to start again with a clean config and new authorization but I always get that message.

**Comment by GrouchyGaijin** [comment] 2017-03-01 02:13
I am getting the same error. Ubuntu 16.04

[error.txt](https://github.com/skilion/onedrive/files/809551/error.txt)

**Comment by Ackis** [comment] 2017-03-01 18:45
I'm not sure if this is the same issue or not, but this error pops up when I try to have a new file uploaded.  Everything downloaded fine without issue.  As the root cause seems to be the same (adding a new file) I thought it might pertain to this ticket.

`onedrive.OneDriveException@src/onedrive.d(367): Peer certificate cannot be authenticated with given CA certificates on handle 1B43940
----------------
??:? std.json.JSONValue onedrive.OneDriveApi.perform() [0x5c0a1e]
??:? std.json.JSONValue onedrive.OneDriveApi.get(const(char)[]) [0x5bf257]
??:? std.json.JSONValue onedrive.OneDriveApi.getDefaultDrive() [0x5bd127]
??:? bool onedrive.OneDriveApi.init() [0x5bc853]
??:? _Dmain [0x5b6f39]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5dfc97]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5dfbc3]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5dfc3c]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5dfbc3]
??:? _d_run_main [0x5dfb27]
??:? main [0x5ba537]
??:? __libc_start_main [0x7e52b82f]
std.net.curl.CurlException@std/net/curl.d(4097): Peer certificate cannot be authenticated with given CA certificates on handle 1B43940
----------------
??:? pure @safe void std.exception.bailOut!(std.net.curl.CurlException).bailOut(immutable(char)[], ulong, const(char[])) [0x63d5ec]
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x63d561]
??:? void std.net.curl.Curl._check(int) [0x6165c4]
??:? int std.net.curl.Curl.perform(std.typecons.Flag!("throwOnError").Flag) [0x616a18]
??:? int std.net.curl.HTTP.perform(std.typecons.Flag!("throwOnError").Flag) [0x613643]
??:? std.json.JSONValue onedrive.OneDriveApi.perform() [0x5c09b6]
??:? std.json.JSONValue onedrive.OneDriveApi.get(const(char)[]) [0x5bf257]
??:? std.json.JSONValue onedrive.OneDriveApi.getDefaultDrive() [0x5bd127]
??:? bool onedrive.OneDriveApi.init() [0x5bc853]
??:? _Dmain [0x5b6f39]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5dfc97]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5dfbc3]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5dfc3c]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5dfbc3]
??:? _d_run_main [0x5dfb27]
??:? main [0x5ba537]
??:? __libc_start_main [0x7e52b82f]
Segmentation fault (core dumped)
`

**Comment by rodan123** [comment] 2017-03-01 23:05
Maybe had been something on MS side. I had same error. Clear now.
I use CRON to sync every hour. Tried the -m option. Won't survive a suspend / resume to RAM.

**Comment by GrouchyGaijin** [comment] 2017-03-02 00:53
I am still getting the error:
$ onedrive -m
Uploading: ./Driggs-Elementary/immunization-records/KaiVaccination_backup.pdf
HTTP request returned status code 400 (Bad Request)
{
    "error": {
        "code": "invalidRequest",
        "message": "Bad Argument"
    }
}
Uploading: ./Driggs-Elementary/immunization-records/KaiVaccination_backup.pdf
HTTP request returned status code 400 (Bad Request)
{
    "error": {
        "code": "invalidRequest",
        "message": "Bad Argument"
    }
}
Uploading: ./Driggs-Elementary/immunization-records/KaiVaccination_backup.pdf
sync.SyncException@src/sync.d(348): HTTP request returned status code 400 (Bad Request)
{
    "error": {
        "code": "invalidRequest",
        "message": "Bad Argument"
    }
}
----------------
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x5c5dba]
??:? void main.performSync(sync.SyncEngine) [0x5b3e86]
??:? _Dmain [0x5b36a2]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5da98e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5da8d8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5da94a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5da8d8]
??:? _d_run_main [0x5da849]
??:? main [0x5b6725]
??:? __libc_start_main [0x22cef82f]
onedrive.OneDriveException@src/onedrive.d(382): HTTP request returned status code 400 (Bad Request)
{
    "error": {
        "code": "invalidRequest",
        "message": "Bad Argument"
    }
}
----------------
??:? std.json.JSONValue onedrive.OneDriveApi.upload(immutable(char)[], immutable(char)[]) [0x5bbff3]
??:? void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x5c86da]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5c8029]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5c7e18]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5c7e18]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5c7e18]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x5c5cb5]
??:? void main.performSync(sync.SyncEngine) [0x5b3e86]
??:? _Dmain [0x5b36a2]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5da98e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5da8d8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5da94a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5da8d8]
??:? _d_run_main [0x5da849]
??:? main [0x5b6725]
??:? __libc_start_main [0x22cef82f]
Segmentation fault (core dumped)

**Comment by PterX** [comment] 2017-03-02 02:47
i am gettting the same error.

**Comment by ryanneph** [comment] 2017-03-02 19:37
Same error for me on Ubuntu 16.04 that began a few days ago:

```
sync.SyncException@src/sync.d(348): HTTP request returned status code 400 (Bad Request)
{
    "error": {
        "code": "invalidRequest",
        "message": "Bad Argument"
    }
}
----------------
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x5ca402]
??:? void main.performSync(sync.SyncEngine) [0x5b7a68]
??:? _Dmain [0x5b722e]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5dfc97]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5dfbc3]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5dfc3c]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5dfbc3]
??:? _d_run_main [0x5dfb27]
??:? main [0x5ba537]
??:? __libc_start_main [0x6e81282f]
onedrive.OneDriveException@src/onedrive.d(382): HTTP request returned status code 400 (Bad Request)
{
    "error": {
        "code": "invalidRequest",
        "message": "Bad Argument"
    }
}
----------------
??:? std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], const(char)[]) [0x5c33d3]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5cc3dd]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5cc574]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5cc574]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x5ca2f1]
??:? void main.performSync(sync.SyncEngine) [0x5b7a68]
??:? _Dmain [0x5b722e]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5dfc97]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5dfbc3]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5dfc3c]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5dfbc3]
??:? _d_run_main [0x5dfb27]
??:? main [0x5ba537]
??:? __libc_start_main [0x6e81282f]
Segmentation fault (core dumped)

```

**Comment by thomasfedb** [comment] 2017-03-03 09:47
Experiencing this issue, appears to reoccur with a specific file, although I can't see anything about the file name or file itself that would be causing an issue.

**Comment by hugomilan** [comment] 2017-03-05 03:17
I confirm this issue. Interestingly, this is happening to the files that are not online. If you manually upload the file to your OneDrive account, you will not observe this error. But then you will observe for the next file that is not online...

**Comment by ngse** [comment] 2017-03-06 00:05
Also experiencing this error when trying to create new local files and have them uploaded. I tested to see if I could edit a local file which had been pulled down from OneDrive and that resulted in the remote copy of the file being removed, but the local changes to the file preserved. It could then not upload the local file due to the initial issue.

The trace for the edit failure follows (not sure where or what the file 4913 was but the action was `vi test.txt` in `./Documents` which explains the `test.txt~`

```
Initializing monitor ...
Monitor directory: .
Monitor directory: ./Documents
Monitor directory: ./Public
Monitor directory: ./Pictures
Monitor directory: ./Email attachments
[M] File changed: ./Documents/4913
Uploading differences ...
Uploading new items ...
./Documents/4913: No such file or directory
[M] File changed: ./Documents/4913
Uploading differences ...
Uploading new items ...
./Documents/4913: No such file or directory
[M] Item deleted: ./Documents/4913
Can't delete an unsynced item
[M] Item moved: ./Documents/test.txt -> ./Documents/test.txt~
Moving remote item: ./Documents/test.txt -> ./Documents/test.txt~
std.file.FileException@/usr/include/dmd/phobos/std/file.d(1293): ./Documents/test.txt~: No such file or directory
----------------
??:? @trusted bool std.file.cenforce!(bool).cenforce(bool, const(char)[], const(char)*, immutable(char)[], ulong) [0x5ac100]
??:? @safe std.datetime.SysTime std.file.timeLastModified!(immutable(char)[]).timeLastModified(immutable(char)[]) [0x5aea19]
??:? void sync.SyncEngine.uploadMoveItem(immutable(char)[], immutable(char)[]) [0x5d5d94]
??:? void main.main(immutable(char)[][]).__dgliteral5(immutable(char)[], immutable(char)[]) [0x5bf0fb]
??:? void monitor.Monitor.update(bool) [0x5c37de]
??:? _Dmain [0x5bec7a]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5e609f]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5e5fc7]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5e6044]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5e5fc7]
??:? _d_run_main [0x5e5f33]
??:? main [0x5c216f]
??:? __libc_start_main [0x996ed82f]
Segmentation fault (core dumped)
```
This is my first use of onedrive on linux so I don't have a previous working state to compare from.

**Comment by erikvschaik** [comment] 2017-03-06 14:35
I can confirm hugomilan's statement that the error occurs when a local file is attempted to be uploaded. The sync from Onedrive to my local computer works fine. A current work-around is to use the web-interface of Onedrive to upload local files.

**Comment by schultzern** [comment] 2017-03-08 12:05
Same issue occur on Cent OS 7

**Comment by kingtiger01** [comment] 2017-03-09 15:40
same here
`Uploading new items ...
Uploading: ./Pictures/20170224_131306-1.jpg
sync.SyncException@src/sync.d(348): HTTP request returned status code 400 (Bad Request)
{
    "error": {
        "code": "invalidRequest",
        "message": "Bad Argument"
    }
}
----------------
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x5c939c]
??:? void main.performSync(sync.SyncEngine) [0x5b6860]
??:? _Dmain [0x5b6022]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5dd336]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5dd27c]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5dd2f2]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5dd27c]
??:? _d_run_main [0x5dd1f6]
??:? main [0x5b9857]
??:? __libc_start_main [0x6563f290]
onedrive.OneDriveException@src/onedrive.d(382): HTTP request returned status code 400 (Bad Request)
{
    "error": {
        "code": "invalidRequest",
        "message": "Bad Argument"
    }
}
----------------
??:? std.json.JSONValue onedrive.OneDriveApi.upload(immutable(char)[], immutable(char)[]) [0x5bf33f]
??:? void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x5cbd97]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5cb6a2]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5cb47d]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5cb47d]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x5c928b]
??:? void main.performSync(sync.SyncEngine) [0x5b6860]
??:? _Dmain [0x5b6022]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5dd336]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5dd27c]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5dd2f2]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5dd27c]
??:? _d_run_main [0x5dd1f6]
??:? main [0x5b9857]
??:? __libc_start_main [0x6563f290]
Segmentation fault (core dumped)`

This is a Severe bug, please fix immediately.

**Comment by thomasfedb** [comment] 2017-03-09 16:40
@kingtiger01 unless you're about to offer a pull request I'd watch your tone.

**Comment by digadri** [comment] 2017-03-10 21:35
works: download
don't work: create new directory or new file in cloud

Fedora release 25 (Twenty Five)
uname -r: 4.9.13-200.fc25.x86_64

dmd downloaded from tar
http://downloads.dlang.org/releases/2.x/2.073.2/dmd.2.073.2.linux.tar.xz

sqlite-3.14.2-1.fc25.x86_64

libcurl-devel-7.51.0-4.fc25.x86_64

**Comment by skilion** [comment] 2017-03-11 10:58
Try again with the latest commit which uses the new Microsoft Graph API.
It is needed to reauth the app with `onedrive --logout`.

**Comment by digadri** [comment] 2017-03-11 11:24
Seemingly same error using last commit or v.1.1.
Steps:
- git clone
- make
- run onedrive in command line without file system modification (no message - ok)
- create new empty directory in .\Documentos\banking: new123

Results: message: "Bad Argument"



[git-clone-output.txt](https://github.com/skilion/onedrive/files/835695/git-clone-output.txt)
[onedrive-output.txt](https://github.com/skilion/onedrive/files/835697/onedrive-output.txt)

**Comment by skilion** [comment] 2017-03-11 12:37
From `onedrive-output.txt` I see that you are not using the latest version: "https://login.live.com/..." is the old endpoint.
Run `sudo make install` after make.

**Comment by digadri** [comment] 2017-03-11 12:54
ok, See new attachments
![screenshot from 2017-03-11 09-49-45](https://cloud.githubusercontent.com/assets/6642328/23823415/b8e17296-0640-11e7-8198-40e95653a4cb.png)
[onedrive-output1.txt](https://github.com/skilion/onedrive/files/835742/onedrive-output1.txt)

**Comment by skilion** [comment] 2017-03-11 13:03
The app is using the old client_id.
If `~/.config/onedrive/config` cointains `client_id`, remove that line.
Make sure that `/usr/local/etc/onedrive.conf` has `client_id = "22c49a0d-d21c-4792-aed1-8f163c982546"`.

**Comment by digadri** [comment] 2017-03-11 13:21
Rigth.
Note: My login is
br.sobrinho (nospam) outlook dot com

and I can login in
https://outlook.live.com/

but not in
https://login.microsoftonline.com/

[onedrive-output2.txt](https://github.com/skilion/onedrive/files/835781/onedrive-output2.txt)

**Comment by skilion** [comment] 2017-03-11 13:46
Try to do remove everything and perform a clean install.
`sudo make uninstall`
`rm -rf ~/.config/onedrive`
Also clear the browser cache and cookies.

**Comment by skilion** [comment] 2017-03-11 14:19
The unauthenticated error was due to a missing scope. Fixed in ac555fd57496d921480c273bd3078cb1c8ebe59c. Reauthorize again with `onedrive --logout`

**Comment by digadri** [comment] 2017-03-11 16:17
Congrats! 
now works for me
[onedrive-output3.txt](https://github.com/skilion/onedrive/files/835928/onedrive-output3.txt)

**Comment by lgfpaula** [comment] 2017-03-13 13:47
Awesome! Works again! Thank you!!!

**Comment by ryanneph** [comment] 2017-03-14 07:21
Works perfectly for me as well after replacing the config file client_id property, rebuilding binary, and performing onedrive --logout. Thanks for the fast work @skilion, much appreciated!

**Closed** 2017-06-26 11:55 UTC

**Comment by farznaj** [comment] 2020-09-29 05:25
I had onedrive working just fine on my linux machine. Today it stopped working. I have many times uninstalled and reinstalled it. Again when I try to sync by typing "onedrive" in terminal, after I enter the response URL, I get this error:

onedrive.OneDriveException@src/onedrive.d(408): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "0bd120ae-47fd-4143-8e4c-f557ed53cd48",
    "error": "invalid_grant",
    "error_codes": [
        9002313
    ],
    "error_description": "AADSTS9002313: Invalid request. Request is malformed or invalid.\r\nTrace ID: 032d178f-2cdd-40d9-9486-936a7f710300\r\nCorrelation ID: 0bd120ae-47fd-4143-8e4c-f557ed53cd48\r\nTimestamp: 2020-09-29 05:24:00Z",
    "error_uri": "https:\/\/login.microsoftonline.com\/error?code=9002313",
    "timestamp": "2020-09-29 05:24:00Z",
    "trace_id": "032d178f-2cdd-40d9-9486-936a7f710300"
}
----------------
src/onedrive.d:33 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x5591f9305cfc]
src/onedrive.d:333 std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], const(char)[]) [0x5591f9305e9e]
src/onedrive.d:252 void onedrive.OneDriveApi.acquireToken(const(char)[]) [0x5591f9304fd1]
src/onedrive.d:237 void onedrive.OneDriveApi.redeemToken(const(char)[]) [0x5591f9304eb6]
src/onedrive.d:84 bool onedrive.OneDriveApi.authorize() [0x5591f9303f12]
src/onedrive.d:64 bool onedrive.OneDriveApi.init() [0x5591f9303d43]
src/main.d:100 _Dmain [0x5591f92fc7b6]


Can you help please.

**Comment by abraunegg** [comment] 2020-09-29 05:44
@farznaj
> I had onedrive working just fine on my linux machine. Today it stopped working. I have many times uninstalled and reinstalled it. Again when I try to sync by typing "onedrive" in terminal, after I enter the response URL, I get this error:
> ...
> Can you help please.

There was a major Microsoft Azure outage today that impacted all Microsoft cloud services. Most likely it stopped working because of this.

Additionally, the 'skilion' repo is defunct and was abandoned in 2018. Do not use this repo.

Your issue is the same as:
* https://github.com/skilion/onedrive/issues/512
* https://github.com/skilion/onedrive/issues/511
* https://github.com/skilion/onedrive/issues/510

The latest and maintained code can be found here: https://github.com/abraunegg/onedrive

#### Major differences / Enhancements:
- Existing bugs with 'skilion' client fixed
- File upload / download validation to ensure data integrity
- Support for SharePoint / Office 365 Shared Libraries 
- Support for OneDrive Business Shared Folders
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change
- Support National Azure Cloud instances

**Comment by tefracky** [comment] 2020-10-14 07:57
The bug is still alive. I wanted to install onedrive on Debian and after paste the response URL, the following error occurs:

`onedrive.OneDriveException@src/onedrive.d(713): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "958a56f6-48b2-4326-a426-547fd7a9cc75",
    "error": "invalid_grant",
    "error_codes": [
        70000
    ],
    "error_description": "AADSTS70000: The provided value for the 'code' parameter is not valid.\r\nTrace ID: 9d86b32a-9913-4d47-a79c-d551c69a4600\r\nCorrelation ID: 958a56f6-48b2-4326-a426-547fd7a9cc75\r\nTimestamp: 2020-10-14 07:54:10Z",
    "error_uri": "https:\/\/login.microsoftonline.com\/error?code=70000",
    "timestamp": "2020-10-14 07:54:10Z",
    "trace_id": "9d86b32a-9913-4d47-a79c-d551c69a4600"
}
----------------
??:? [0x92f03]
??:? [0x921cb]
??:? [0x92a1b]
??:? [0x9155b]
??:? [0x9afb3]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0xb687bb17]
??:? _d_run_main [0xb687b8af]
??:? __libc_start_main [0xb65b9717]
`

**Comment by abraunegg** [comment] 2020-10-14 08:02
@tefracky
You have installed old code. This repo is dead & this bug is most certainly fixed - please read the post above yours for details.

**Comment by ValentinaViafara** [comment] 2021-04-09 01:23
I used this link for resolve this problem https://github.com/skilion/onedrive/issues/511

Here explain the steps for installing correctly OneDrive, i hope that this can helo you.
