### ISSUE TITLE
HTTP request returned status code 500 (Internal Server Error)

### ISSUE THREAD

**Issue by lkhphuc** [skilion/onedrive#33] opened 2016-02-06 16:16 UTC
Hello, I have problem when running onedrive. Everytime I run onedrive, it's return internal server error code.  Here are the result:
HTTP request returned status code 500 (Internal Server Error)
HTTP request returned status code 500 (Internal Server Error)
## sync.SyncException@src/sync.d(106): HTTP request returned status code 500 (Internal Server Error)

??:? void sync.SyncEngine.applyDifferences() [0x5cbe1f]
??:? void main.performSync(sync.SyncEngine) [0x5bdc1f]
??:? _Dmain [0x5bd4c2]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5d8a9a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d89d8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])_).runAll() [0x5d8a56]
??:? void rt.dmain2._d_run_main(int, char__, extern (C) int function(char[][])_).tryExec(scope void delegate()) [0x5d89d8]
??:? _d_run_main [0x5d8935]
??:? main [0x5bf91d]
??:? __libc_start_main [0x59221a3f]
## onedrive.OneDriveException@src/onedrive.d(337): HTTP request returned status code 500 (Internal Server Error)

??:? void onedrive.OneDriveApi.checkHttpCode() [0x5c4e08]
??:? std.json.JSONValue onedrive.OneDriveApi.get(const(char)[]) [0x5c3b40]
??:? void sync.SyncEngine.applyDifferences() [0x5cbbf8]
??:? void main.performSync(sync.SyncEngine) [0x5bdc1f]
??:? _Dmain [0x5bd4c2]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5d8a9a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d89d8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])_).runAll() [0x5d8a56]
??:? void rt.dmain2._d_run_main(int, char__, extern (C) int function(char[][])_).tryExec(scope void delegate()) [0x5d89d8]
??:? _d_run_main [0x5d8935]
??:? main [0x5bf91d]
??:? __libc_start_main [0x59221a3f]`

**Update:**
When I run: onedrive -v --resync, I notice that the HTML error code 500 will be returned at a particular folder, every single time. 

Thanks in advance.

**Comment by fboaventura** [comment] 2016-03-06 15:52
I've got the same error here. The log is attached.

[onedrive_error.txt](https://github.com/skilion/onedrive/files/160405/onedrive_error.txt)

**Comment by jmayday** [comment] 2017-02-26 09:34
Same issue here. I left onedrive executed with -v parameter. It was able to download something like 33GB then it crashed.

```
AE79DFC25CCEEEFF!12984 Obraz 071.jpg
Downloading: ./Obrazy/Sebastian - zdjęcia/panasonic/jaf/Obraz 071.jpg
sync.SyncException@src/sync.d(118): HTTP request returned status code 500 (Internal Server Error)
{
    "error": {
        "code": "generalException",
        "message": "An error occurred in the data store."
    }
}
----------------
??:? void sync.SyncEngine.applyDifferences() [0x5c88aa]
??:? void main.performSync(sync.SyncEngine) [0x5b7c5b]
??:? _Dmain [0x5b7432]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5dea13]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5de93b]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5de9b8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5de93b]
??:? _d_run_main [0x5de8a7]
??:? main [0x5bac67]
??:? __libc_start_main [0x6f7ac400]
onedrive.OneDriveException@src/onedrive.d(382): HTTP request returned status code 500 (Internal Server Error)
{
    "error": {
        "code": "generalException",
        "message": "An error occurred in the data store."
    }
}
----------------
??:? std.json.JSONValue onedrive.OneDriveApi.get(const(char)[]) [0x5bf9e5]
??:? void sync.SyncEngine.applyDifferences() [0x5c854c]
??:? void main.performSync(sync.SyncEngine) [0x5b7c5b]
??:? _Dmain [0x5b7432]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5dea13]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5de93b]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5de9b8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5de93b]
??:? _d_run_main [0x5de8a7]
??:? main [0x5bac67]
??:? __libc_start_main [0x6f7ac400]
fish: 'onedrive -v' zakończony sygnałem SIGSEGV (Address boundary error)
```

**Comment by skilion** [comment] 2018-01-02 16:46
Error 500 corresponds to an internal server error of OneDrive so it is a bit tricky to debug. Usually retrying a few times is enough to make it go away. However if you are stuck in a situation where it happens systematically, please describe which are the steps to reproduce the error.

**Comment by abraunegg** [comment] 2018-04-23 06:38
I have added a number of checks for various upload aspects in #314 - can you check if this is still an issue for you?

**Comment by abraunegg** [comment] 2018-05-06 20:18
@lkhphuc  @fboaventura @jmayday 
Can you provide an update to this issue? If this is no longer relevant, please can you close this case.

**Comment by abraunegg** [comment] 2018-05-26 03:03
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive

**Closed** 2019-11-12 13:57 UTC
