### ISSUE TITLE
Failure when receiving data from the peer on handle

### ISSUE THREAD

**Issue by AlNedorezov** [skilion/onedrive#11] opened 2015-12-16 13:42 UTC
After running onedrive with -v switch got the following output:

```
Downloading: ./Literature/Программирование/Разное/Khorstman_K_-_Scala_Dlya_Neterpelivykh_-_2013.pdf
std.net.curl.CurlException@patch/std_net_curl.d(4037): Failure when receiving data from the peer on handle 2197E10
----------------
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x56bb5a]
??:? void std.net.curl.Curl._check(int) [0x584c12]
??:? int std.net.curl.HTTP.perform(std.typecons.Flag!("throwOnError").Flag) [0x5802df]
??:? void onedrive.OneDriveApi.download(const(char)[], immutable(char)[]) [0x5b5d70]
??:? void onedrive.OneDriveApi.downloadById(const(char)[], immutable(char)[]) [0x5b3ae4]
??:? void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x5bebc1]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x5be6f6]
??:? void sync.SyncEngine.applyDifferences() [0x5bd8b1]
??:? void main.performSync(sync.SyncEngine) [0x5af7d7]
??:? _Dmain [0x5af10f]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5ca93e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5ca894]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5ca8fa]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5ca894]
??:? _d_run_main [0x5ca7f1]
??:? main [0x5b14ad]
??:? __libc_start_main [0x5552ec4]
```

**Comment by skilion** [comment] 2015-12-17 09:44
Did you try to do a resync `onedrive -v --resync` ?

**Comment by AlNedorezov** [comment] 2015-12-17 13:01
Yes, got the same error, but on the different file:

```
Downloading: ./Projects/Innopolis/2015 - Fall/User Experience and Interface Design fundamentals/Project/Usability tests/Participant 5.mov
std.net.curl.CurlException@patch/std_net_curl.d(4037): Failure when receiving data from the peer on handle 10E0C40
----------------
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x56bb5a]
??:? void std.net.curl.Curl._check(int) [0x584c12]
??:? int std.net.curl.HTTP.perform(std.typecons.Flag!("throwOnError").Flag) [0x5802df]
??:? void onedrive.OneDriveApi.download(const(char)[], immutable(char)[]) [0x5b5d70]
??:? void onedrive.OneDriveApi.downloadById(const(char)[], immutable(char)[]) [0x5b3ae4]
??:? void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x5bebc1]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x5be6f6]
??:? void sync.SyncEngine.applyDifferences() [0x5bd8b1]
??:? void main.performSync(sync.SyncEngine) [0x5af7d7]
??:? _Dmain [0x5af10f]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5ca93e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5ca894]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5ca8fa]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5ca894]
??:? _d_run_main [0x5ca7f1]
??:? main [0x5b14ad]
??:? __libc_start_main [0x136d8ec4]
```

**Comment by skilion** [comment] 2015-12-29 19:33
The error doesn't seem to be related to the application logic.
Do you have an instable connection ?
Do you have a slow internet connection ? Long downloads can be reset by the server.

**Comment by colombojrj** [comment] 2016-02-04 08:45
Hi,

I also experienced this issue using Ubuntu 14.04. I solved it (or at least it seems solved) by removing libcurl GNUTLS flavour (libcurl4-gnutls-dev package) e installing libcurl OPENSSL flavour (libcurl4-openssl-dev package).

Hope it helps you. Seeya!

**Comment by niuin** [comment] 2017-01-08 09:52
I also had the same problem, but I solved it.
The cause was the version of the DMD compiler.

When compiling with DMD 2.072.2.
An error occurs in a file with a large size.

Compiling with DMD Beta 2.073.0 - b1, this phenomenon disappears and is comfortable!

**Comment by thomasfedb** [comment] 2017-01-16 08:34
Currently experiencing this error also. Is there a fix?

**Comment by jmayday** [comment] 2017-02-26 14:12
Also happend to me on Fedora 24. 

```
dmd-2.073.1-0.x86_64
libsqlite3x-devel-20071018-19.fc24.x86_64
libcurl-devel-7.51.0-4.fc25.x86_64
```


```
std.net.curl.CurlException@std/net/curl.d(4097): Failure when receiving data from the peer on handle 1C51100
----------------
??:? pure @safe void std.exception.bailOut!(std.net.curl.CurlException).bailOut(immutable(char)[], ulong, const(char[])) [0x644d58]
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x644ccd]
??:? void std.net.curl.Curl._check(int) [0x618a24]
??:? int std.net.curl.Curl.perform(std.typecons.Flag!("throwOnError").Flag) [0x618e78]
??:? int std.net.curl.HTTP.perform(std.typecons.Flag!("throwOnError").Flag) [0x615a9b]
??:? void onedrive.OneDriveApi.download(const(char)[], immutable(char)[]) [0x5c005b]
??:? void onedrive.OneDriveApi.downloadById(const(char)[], immutable(char)[]) [0x5bdcf0]
??:? void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x5c9c2c]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x5c9662]
??:? void sync.SyncEngine.applyDifferences() [0x5c86aa]
??:? void main.performSync(sync.SyncEngine) [0x5b7c5b]
??:? _Dmain [0x5b7432]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5dea13]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5de93b]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5de9b8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5de93b]
??:? _d_run_main [0x5de8a7]
??:? main [0x5bac67]
??:? __libc_start_main [0x339bb400]
```

**Comment by ibrokemypie** [comment] 2017-06-21 06:22
```
017-06-21_06:21:25.36971 Downloading: Personal/Roms/Game Library/Library.storedata-wal
2017-06-21_06:21:28.09896 std.net.curl.CurlException@std/net/curl.d(4097): Failure when receiving data from the peer on handle 191D510
2017-06-21_06:21:28.09899 ----------------
2017-06-21_06:21:28.10172 ??:? pure @safe void std.exception.bailOut!(std.net.curl.CurlException).bailOut(immutable(char)[], ulong, const(char[])) [0x653c38]
2017-06-21_06:21:28.10179 ??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x653bb1]
2017-06-21_06:21:28.10179 ??:? void std.net.curl.Curl._check(int) [0x62b3a2]
2017-06-21_06:21:28.10183 ??:? int std.net.curl.Curl.perform(std.typecons.Flag!("throwOnError").Flag) [0x62b7dc]
2017-06-21_06:21:28.10186 ??:? int std.net.curl.HTTP.perform(std.typecons.Flag!("throwOnError").Flag) [0x628563]
2017-06-21_06:21:28.10188 ??:? void onedrive.OneDriveApi.download(const(char)[], immutable(char)[]) [0x5cbdff]
2017-06-21_06:21:28.10191 ??:? void onedrive.OneDriveApi.downloadById(const(char)[], immutable(char)[]) [0x5c9e6f]
2017-06-21_06:21:28.10194 ??:? void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x5da6ff]
2017-06-21_06:21:28.10196 ??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x5da14b]
2017-06-21_06:21:28.10197 ??:? void sync.SyncEngine.applyDifferences() [0x5d9404]
2017-06-21_06:21:28.10197 ??:? void main.performSync(sync.SyncEngine) [0x5c4dab]
2017-06-21_06:21:28.10199 ??:? _Dmain [0x5c4a0e]
2017-06-21_06:21:28.10201 ??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5f1686]
2017-06-21_06:21:28.10207 ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5f15d0]
2017-06-21_06:21:28.10211 ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5f1642]
2017-06-21_06:21:28.10218 ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5f15d0]
2017-06-21_06:21:28.10218 ??:? _d_run_main [0x5f1541]
2017-06-21_06:21:28.10219 ??:? main [0x5c7d9d]
2017-06-21_06:21:28.10219 ??:? __libc_start_main [0xc3a5d510]
```

**Comment by geoffhenry** [comment] 2017-09-13 10:09
In case anyone goes googling for it, I had a similar issue with uploads on Centos 6.9 - smaller files would sync fine but larger ones (over about 20MB) would fail with "Failure when uploading data to the peer on handle ..." on the first chunk, every time. Watching my network io I could see that data continued to go out, but it looked like libcurl wasn't properly chunking the file stream and was instead trying to send the whole file in the PUT payload for the first chunk. Updating libcurl-devel to a more recent version (from the city-fan repo) resolved the problem.

**Comment by abraunegg** [comment] 2018-05-06 20:18
@AlNedorezov 
Can you provide an update to this case? If no longer an issue please can you close out this issue.

**Comment by lovenemesis** [comment] 2018-05-18 05:31
On Fedora 28 x86_64 with libcurl 7.59.0, I'm still seeing this issue with large file. onedrive was compiled with dmd-2.080.0.

**Comment by abraunegg** [comment] 2018-05-19 22:17
@lovenemesis 
What version of the code are you using? Are you using the #314 branch?

The skilion base is unmaintained and does not have the fix.

**Comment by lovenemesis** [comment] 2018-05-21 01:45
@abraunegg No. Allow me to switch to your branch and give another try.

Thanks,

**Comment by abraunegg** [comment] 2018-05-22 16:19
@lovenemesis 
Any update? If not please close this case

**Comment by abraunegg** [comment] 2018-05-26 03:04
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive

**Closed** 2018-07-17 10:23 UTC
