### ISSUE TITLE
x86_64-suse-linux/bin/ld: cannot find -lphobos2

### ISSUE THREAD

**Issue by crmne** [skilion/onedrive#168] opened 2017-03-15 13:32 UTC
Same as #19 , but with the latest version of onedrive.

    $ ls /usr/lib64/*phobos*
    /usr/lib64/libphobos2-ldc-debug.so         /usr/lib64/libphobos2.so
    /usr/lib64/libphobos2-ldc-debug.so.2.0.68  /usr/lib64/libphobos2.so.0.71
    /usr/lib64/libphobos2-ldc-debug.so.68      /usr/lib64/libphobos2.so.0.71.0
    /usr/lib64/libphobos2-ldc.so               /usr/lib64/libphobos2.so.0.73
    /usr/lib64/libphobos2-ldc.so.2.0.68        /usr/lib64/libphobos2.so.0.73.1
    /usr/lib64/libphobos2-ldc.so.68

    $ make
    dmd -O -release -inline -boundscheck=off -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/upload.d src/util.d
    /usr/lib64/gcc/x86_64-suse-linux/6/../../../../x86_64-suse-linux/bin/ld: cannot find -lphobos2
    collect2: error: ld returned 1 exit status
    Error: linker exited with status 1
    make: *** [Makefile:18: onedrive] Error 1

**Comment by crmne** [comment] 2017-03-15 13:32
$ dmd --version
    DMD64 D Compiler v2.073.1
    Copyright (c) 1999-2016 by Digital Mars written by Walter Bright

**Comment by Tekki** [comment] 2017-03-15 13:51
Did you install libcurl-devel and sqlite3-devel (that's how these packages are called on Opensuse)?

**Comment by Scimmia22** [comment] 2017-03-18 03:41
Duplicate of #150

**Comment by cbcoutinho** [comment] 2017-11-24 03:24
Duplicate of my issue: #252 - I needed to download some related devel packages.

**Comment by skilion** [comment] 2018-01-02 19:23
The error is related to the compilation environment, it is not a problem of the application itself

**Closed by skilion** 2018-01-02 19:23 UTC

**Comment by Aquarian-Age** [comment] 2019-01-25 22:33
zypper in  phobos-devel-static phobos-devel  libphobos2-0_79

**Comment by abraunegg** [comment] 2019-01-25 23:20
@Aquarian-Age

FYI, the 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests may not be looked at under this github repository. Regarding SuSE build instructions - refer to: https://github.com/abraunegg/onedrive/blob/master/README.md#dependencies-opensuse-leap-150

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.
