### ISSUE TITLE
onedrive not syncing "hidden" directories

### ISSUE THREAD

**Issue by ELadner** [skilion/onedrive#330] opened 2018-04-04 13:41 UTC
I have several cases where Unix style "hidden" directories (like .foo) are not being synced.  ".git" folders are notably absent.  They are visible when viewing from a Windows machine, or the OneDrive web interface, but do not showup in the directory on the Linux side.

**Comment by abraunegg** [comment] 2018-04-10 23:35
The cause of this is the following in sync.d:

```selectiveSync.isNameExcluded```

The function in selective.d reads:

```
bool isNameExcluded(string name)
{
     return !name.matchFirst(mask).empty;
}
```

Anything with a . at the start of the name returns false - thus this is why it is excluded. I am looking to see how best to change this function so that for . files / directories it returns true.

I tested by commenting out ```selectiveSync.isNameExcluded``` in uploadNewItems() within sync.d and it was able to sync .git folders and contents of those folders - so fixing the selective.d function is the right approach here.

**Comment by abraunegg** [comment] 2018-04-11 03:04
Pushed a patch to my pull #314 request that fixes this for me. If you can test that would be greatly appreciated.

**Comment by abraunegg** [comment] 2018-04-23 09:42
@ELadner 

Any update?

**Comment by abraunegg** [comment] 2018-04-23 19:34
No worries. Can you close this case then?

**Closed** 2018-04-23 21:07 UTC
