### ISSUE TITLE
Service is constantly shutting down

### ISSUE THREAD

**Issue by h0wdyd3wdy** [skilion/onedrive#78] opened 2016-07-01 19:15 UTC
The onedrive service is constantly shutting down, as I have to often ps auxw |grep to see if it's still running.  It may sometimes run for days, but then this occurs.  

Is it possible to have some kind of system tray notification?

**Comment by quirinux** [comment] 2016-07-04 14:04
@h0wdyd3wdy dude, do you have any log? it would help

**Comment by h0wdyd3wdy** [comment] 2016-07-15 03:45
Where would I be looking for the log?  Like, which log, specifically?

It often seems to be related to changing of filenames, etc.

**Comment by marcvantzand** [comment] 2016-07-19 08:05
here it happens when internet has an hiccup like when the lease is renewed by the provider Here the log:
maarten@maarten-acer> /usr/local/bin/onedrive
Downloading: ./Pictures/Camera Roll/20151002_125242.jpg
/20151011_153643.jpg
................
Downloading: ./Pictures/Camera Roll/20151016_145528.jpg
std.net.curl.CurlTimeoutException@std/net/curl.d(4039): Timeout was reached on handle 206EEC0
----------------
??:? pure @safe void std.exception.bailOut!(std.net.curl.CurlTimeoutException).bailOut(immutable(char)[], ulong, const(char[])) [0x60a519]
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlTimeoutException, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x60a495]
??:? void std.net.curl.Curl._check(int) [0x5e75e5]
??:? int std.net.curl.Curl.perform(std.typecons.Flag!("throwOnError").Flag) [0x5e7a48]
??:? int std.net.curl.HTTP.perform(std.typecons.Flag!("throwOnError").Flag) [0x5e4807]
??:? void onedrive.OneDriveApi.download(const(char)[], immutable(char)[]) [0x5a204f]
??:? void onedrive.OneDriveApi.downloadById(const(char)[], immutable(char)[]) [0x59ff0f]
??:? void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x5ab019]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x5aab6b]
??:? void sync.SyncEngine.applyDifferences() [0x5a9eea]
??:? void main.performSync(sync.SyncEngine) [0x59bda3]
??:? _Dmain [0x59b513]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5b5dee]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5b5d38]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5b5daa]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5b5d38]
??:? _d_run_main [0x5b5ca9]
??:? main [0x59da0d]
??:? __libc_start_main [0xe40cb24]

it does not go to sleep but it terminates.

hope it is any useful , keep up the good work !

**Comment by chiwhalee** [comment] 2016-07-25 11:35
I've got the same issue.

**Comment by h0wdyd3wdy** [comment] 2016-07-26 04:23
Ok, I have had to switch to running it -m in a console window, as it often shuts down on operations.  It seems moving/renaming files and folders often results in segfaults, for one.

Also, sometimes when updating a file, it uploads the new version with -hostname at the end, instead of overwriting.

**Comment by h0wdyd3wdy** [comment] 2016-07-27 18:27
I just put a file with a long name
"foo bar foo boo foo bar.pdf" or something like that, with spaces, on my local drive.

It kept segfaulting oned until I renamed the file to something shorter with _

**Comment by rodamilans** [comment] 2016-12-15 14:07
I've got the same issue too.

**Comment by ibrokemypie** [comment] 2017-07-06 08:58
```
2374F7E55D3E5741!64297 origin
The item has not changed
2374F7E55D3E5741!111088 master
The item is already present
2374F7E55D3E5741!111118 cm-13.0
The item is already present
sync.SyncException@src/sync.d(182): Timeout was reached on handle 14A0950
----------------
??:? void sync.SyncEngine.applyDifferences() [0x5d5d51]
??:? void main.performSync(sync.SyncEngine) [0x5c4b8b]
??:? _Dmain [0x5c4404]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0x5eb976]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5eb8c0]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5eb932]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5eb8c0]
??:? _d_run_main [0x5eb83e]
??:? main [0x5c82ad]
??:? __libc_start_main [0xd1801510]
onedrive.OneDriveException@src/onedrive.d(380): Timeout was reached on handle 14A0950
----------------
??:? std.json.JSONValue onedrive.OneDriveApi.perform() [0x5cd2cb]
??:? std.json.JSONValue onedrive.OneDriveApi.get(const(char)[], bool) [0x5cbb72]
??:? std.json.JSONValue onedrive.OneDriveApi.viewChangesByPath(const(char)[], const(char)[]) [0x5ca06c]
??:? void sync.SyncEngine.applyDifferences() [0x5d593c]
??:? void main.performSync(sync.SyncEngine) [0x5c4b8b]
??:? _Dmain [0x5c4404]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0x5eb976]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5eb8c0]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5eb932]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5eb8c0]
??:? _d_run_main [0x5eb83e]
??:? main [0x5c82ad]
??:? __libc_start_main [0xd1801510]
std.net.curl.CurlTimeoutException@std/net/curl.d(4308): Timeout was reached on handle 14A0950
----------------
??:? pure @safe void std.exception.bailOut!(std.net.curl.CurlTimeoutException).bailOut(immutable(char)[], ulong, const(char[])) [0x650fa0]
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlTimeoutException, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x650f19]
??:? void std.net.curl.Curl._check(int) [0x624c4d]
??:? int std.net.curl.Curl.perform(std.typecons.Flag!("throwOnError").Flag) [0x625098]
??:? int std.net.curl.HTTP.perform(std.typecons.Flag!("throwOnError").Flag) [0x621e77]
??:? std.json.JSONValue onedrive.OneDriveApi.perform() [0x5cd264]
??:? std.json.JSONValue onedrive.OneDriveApi.get(const(char)[], bool) [0x5cbb72]
??:? std.json.JSONValue onedrive.OneDriveApi.viewChangesByPath(const(char)[], const(char)[]) [0x5ca06c]
??:? void sync.SyncEngine.applyDifferences() [0x5d593c]
??:? void main.performSync(sync.SyncEngine) [0x5c4b8b]
??:? _Dmain [0x5c4404]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0x5eb976]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5eb8c0]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5eb932]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5eb8c0]
??:? _d_run_main [0x5eb83e]
??:? main [0x5c82ad]
??:? __libc_start_main [0xd1801510]
zsh: segmentation fault  onedrive -v --resync

```

**Comment by skilion** [comment] 2018-01-10 11:56
Duplicate of #11

**Closed by skilion** 2018-01-10 11:56 UTC
