### ISSUE TITLE
Crash when deleting a file

### ISSUE THREAD

**Issue by esaintpierre** [skilion/onedrive#122] opened 2016-11-21 16:12 UTC
One drive crashes when trying to delete a file:

`Deleting remote item: ./Documentos/UdelosAndes/Econometria/2016-1/Examen recuperativo.lyx~
HTTP request returned status code 412 (Precondition Failed)
Deleting remote item: ./Documentos/UdelosAndes/Econometria/2016-1/Examen recuperativo.lyx~
HTTP request returned status code 412 (Precondition Failed)
Deleting remote item: ./Documentos/UdelosAndes/Econometria/2016-1/Examen recuperativo.lyx~
sync.SyncException@src/sync.d(352): HTTP request returned status code 412 (Precondition Failed)
----------------
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x81be044]
??:? void main.performSync(sync.SyncEngine) [0x81b16a8]
??:? _Dmain [0x81b0e23]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x81c8832]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x81c8795]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x81c87ee]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x81c8795]
??:? _d_run_main [0x81c871e]
??:? main [0x81b2fb6]
??:? __libc_start_main [0xb7467af2]
onedrive.OneDriveException@src/onedrive.d(337): HTTP request returned status code 412 (Precondition Failed)
----------------
??:? void onedrive.OneDriveApi.checkHttpCode() [0x81b764d]
??:? void onedrive.OneDriveApi.del(const(char)[]) [0x81b6bc8]
??:? void sync.SyncEngine.uploadDeleteItem(itemdb.Item, const(char)[]) [0x81c0213]
??:? void sync.SyncEngine.uploadFileDifferences(itemdb.Item, immutable(char)[]) [0x81bf006]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x81be23d]
??:? void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0x81be34f]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x81be178]
??:? void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0x81be34f]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x81be178]
??:? void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0x81be34f]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x81be178]
??:? void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0x81be34f]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x81be178]
??:? void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0x81be34f]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x81be178]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x81bdf6f]
??:? void main.performSync(sync.SyncEngine) [0x81b16a8]
??:? _Dmain [0x81b0e23]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x81c8832]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x81c8795]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x81c87ee]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x81c8795]
??:? _d_run_main [0x81c871e]
??:? main [0x81b2fb6]
??:? __libc_start_main [0xb7467af2]
Violación de segmento
`

**Comment by ChrisLane** [comment] 2016-11-21 18:49
Duplicate of #118

**Comment by esaintpierre** [comment] 2016-11-23 21:01
Fixed after deleting the file "by hand" in OneDrive and after that making a resync.

**Comment by skilion** [comment] 2016-12-28 23:42
Fixed in 0afb6fa3923066f46c531f33e175011cd69e06a8

**Closed by skilion** 2016-12-28 23:42 UTC
