### ISSUE TITLE
Memory access violation

### ISSUE THREAD

**Issue by OliverKohlDSc** [skilion/onedrive#184] opened 2017-04-16 04:55 UTC
After starting onedrive I get a memory access violation.

Loading config ...
Deleting the saved status ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/oliver/OneDrive
Initializing the Synchronization Engine ...
Applying differences ...
101B7A0020ADBE13!104 root
The item is already present
.: Operation not permitted
Applying differences ...
101B7A0020ADBE13!104 root
The item is already present
.: Operation not permitted
Applying differences ...
101B7A0020ADBE13!104 root
The item is already present
sync.SyncException@src/sync.d(130): .: Operation not permitted
----------------
??:? void sync.SyncEngine.applyDifferences() [0xd29542b1]
??:? void main.performSync(sync.SyncEngine) [0xd2943673]
??:? _Dmain [0xd294323d]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0xd296a0f7]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xd296a01f]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0xd296a09c]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xd296a01f]
??:? _d_run_main [0xd2969f8b]
??:? main [0xd2946859]
??:? __libc_start_main [0x158492b0]
std.file.FileException@/usr/include/dmd/phobos/std/file.d(1192): .: Operation not permitted
----------------
??:? @trusted bool std.file.cenforce!(bool).cenforce(bool, const(char)[], const(char)*, immutable(char)[], ulong) [0xd29340db]
??:? @safe void std.file.setTimes!(immutable(char)[]).setTimes(immutable(char)[], std.datetime.SysTime, std.datetime.SysTime) [0xd293b236]
??:? void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0xd2954d4e]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0xd2954c16]
??:? void sync.SyncEngine.applyDifferences() [0xd295404a]
??:? void main.performSync(sync.SyncEngine) [0xd2943673]
??:? _Dmain [0xd294323d]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0xd296a0f7]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xd296a01f]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0xd296a09c]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xd296a01f]
??:? _d_run_main [0xd2969f8b]
??:? main [0xd2946859]
??:? __libc_start_main [0x158492b0]
./onedrive.sh: Zeile 44: 29684 Speicherzugriffsfehler  /usr/local/bin/onedrive -m -v --resync

It seems that the problem is not related to dmesg itself (echo 0 > /proc/sys/kernel/dmesg_restrict).

oliver@vm:~/Scripts$ uname -a
Linux vm 4.9.0-2-amd64 #1 SMP Debian 4.9.13-1 (2017-02-27) x86_64 GNU/Linux
oliver@vm:~/Scripts$ cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Thanks Oliver

**Comment by Alwinius** [comment] 2017-09-19 16:05
Did you find a solution or a workaround for this? It happens to me too on a rather fresh installed Kubuntu 17.10.

**Comment by Alwinius** [comment] 2017-09-19 17:05
I fixed it by authorising OneDrive first with sudo and then moving /usr/lib/systemd/user/onedrive.service to /etc/systemd/system/ and adding Environment="HOME=/home/username" to the service-section. Then I can just enable it as a system-service with systemctl enable onedrive

**Comment by skilion** [comment] 2018-01-10 14:49
Duplicate of #219

**Closed by skilion** 2018-01-10 14:49 UTC
