### ISSUE TITLE
Filling up syslog

### ISSUE THREAD

**Issue by ricwtk** [skilion/onedrive#51] opened 2016-04-27 08:42 UTC
I installed onedrive yesterday and today I realised that syslog.1 is filled with Enter the response uri: up to 33 GB.

I supposed this will only occur once as it's for the setup, and I can solve it by removing the log. But I think it shouldn't be there at first place.

**Comment by GrouchyGaijin** [comment] 2016-04-27 12:39
I would like to check if my log is filling up too.  Where is that log located, please?

**Comment by ricwtk** [comment] 2016-04-27 13:17
In Ubuntu, it's /var/log/syslog for today's syslog, /var/log/syslog.1 for yesterday's. I suppose it only happens when you need to provide permission to the application to access your onedrive account.

Forgot to mention, this is on Ubuntu 16.04.

**Comment by GrouchyGaijin** [comment] 2016-04-27 13:37
Thanks, I am on 16.04 too.
I have sys logs going back 5 days, although the one from earlier than yesterday are in gz archives.
In any case, the largest one is yesterday's which is 1.5 megabytes.

**Comment by ricwtk** [comment] 2016-04-27 13:52
Perhaps it only happens for first-time log in?

**Comment by Enkouyami** [comment] 2016-04-29 10:30
Couldn't reproduce.

**Comment by skilion** [comment] 2016-06-30 10:55
It happen when the app is not authenticated but the service is enabled.
Fixed in 7d700e1

**Closed by skilion** 2016-06-30 10:55 UTC

**Comment by droberts-athena** [comment] 2024-05-17 02:36
This just happened to me, the onedrive systemd service spammed 40GB of logs overnight, repeating this message hundreds of times a second:

```
ERROR: OneDrive returned an error with the following message:
Error Message: Error in the HTTP2 framing layer on handle 
Calling Function: perform()
```

And then afterwards it filled up my notifications with this error every 3 seconds:

`ERROR: Check your configuration as your refresh_token may be empty or invalid. You may need to issue a --reauth and re-authorise this client.`

**Comment by abraunegg** [comment] 2024-05-17 02:39
@droberts-athena 

> This just happened to me, the onedrive systemd service spammed 40GB of logs overnight, repeating this message hundreds of times a second:
> 
> ```
> ERROR: OneDrive returned an error with the following message:
> Error Message: Error in the HTTP2 framing layer on handle 
> Calling Function: perform()
> ```
> 
> And then afterwards it filled up my notifications with this error every 3 seconds:
> 
> `ERROR: Check your configuration as your refresh_token may be empty or invalid. You may need to issue a --reauth and re-authorise this client.`

Please post your question or problem here: https://github.com/abraunegg/onedrive ..

You are *not* using the client found here.

**Comment by droberts-athena** [comment] 2024-05-17 02:42
Oops, you're right, thanks, I'll repost the issue there
