### ISSUE TITLE
Error renaming (moving) file

### ISSUE THREAD

**Issue by marcoscmonteiro** [skilion/onedrive#147] opened 2017-01-25 15:34 UTC
Onedrive stops work after renaming file. When I restarted the service the file was duplicated. I pasted bellow journalctl log (running Ubuntu 16.10):

-- Logs begin at qua 2017-01-25 13:06:48 BRST. --
jan 25 13:06:57 marcos-laptop systemd[1862]: Started OneDrive Free Client.
jan 25 13:08:15 marcos-laptop onedrive[1882]: Uploading: ./Apartamentos/Parque Laranjeiras - Pinheiro Machado 22-Bl3-310/IPTU/1485356674692.jpg
jan 25 13:08:32 marcos-laptop onedrive[1882]: Moving remote item: ./Apartamentos/Parque Laranjeiras - Pinheiro Machado 22-Bl3-310/IPTU/1485356674692.jpg -> ./Apartamentos/Parque Laranjeiras - Pinheiro Machado 22-Bl3-310/IPTU/IPTU 2017 - Pq Laranjeiras - Comprovante de Pagto.jpg
jan 25 13:08:32 marcos-laptop onedrive[1882]: onedrive.OneDriveException@src/onedrive.d(382): HTTP request returned status code 412 (Precondition Failed)
jan 25 13:08:32 marcos-laptop onedrive[1882]: {
jan 25 13:08:32 marcos-laptop onedrive[1882]:     "error": {
jan 25 13:08:32 marcos-laptop onedrive[1882]:         "code": "notAllowed",
jan 25 13:08:32 marcos-laptop onedrive[1882]:         "innererror": {
jan 25 13:08:32 marcos-laptop onedrive[1882]:             "code": "preconditionFailed"
jan 25 13:08:32 marcos-laptop onedrive[1882]:         },
jan 25 13:08:32 marcos-laptop onedrive[1882]:         "message": "ETag does not match current item's value"
jan 25 13:08:32 marcos-laptop onedrive[1882]:     }
jan 25 13:08:32 marcos-laptop onedrive[1882]: }
jan 25 13:08:32 marcos-laptop onedrive[1882]: ----------------
jan 25 13:08:32 marcos-laptop onedrive[1882]: ??:? std.json.JSONValue onedrive.OneDriveApi.patch!(char).patch(const(char)[], const(char)[]) [0xa75db89b]
jan 25 13:08:32 marcos-laptop onedrive[1882]: ??:? void sync.SyncEngine.uploadMoveItem(immutable(char)[], immutable(char)[]) [0xa75e6cfa]
jan 25 13:08:32 marcos-laptop onedrive[1882]: ??:? void main.main(immutable(char)[][]).__dgliteral5(immutable(char)[], immutable(char)[]) [0xa75d0223]
jan 25 13:08:32 marcos-laptop onedrive[1882]: ??:? void monitor.Monitor.update(bool) [0xa75d442e]
jan 25 13:08:32 marcos-laptop onedrive[1882]: ??:? _Dmain [0xa75cfda6]
jan 25 13:08:32 marcos-laptop onedrive[1882]: ??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0xa75f84d7]
jan 25 13:08:32 marcos-laptop onedrive[1882]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xa75f8403]
jan 25 13:08:32 marcos-laptop onedrive[1882]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0xa75f847c]
jan 25 13:08:32 marcos-laptop onedrive[1882]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xa75f8403]
jan 25 13:08:32 marcos-laptop onedrive[1882]: ??:? _d_run_main [0xa75f8367]
jan 25 13:08:32 marcos-laptop onedrive[1882]: ??:? main [0xa75d2d6f]
jan 25 13:08:32 marcos-laptop onedrive[1882]: ??:? __libc_start_main [0x26ae43f0]
jan 25 13:08:32 marcos-laptop systemd[1862]: onedrive.service: Main process exited, code=dumped, status=11/SEGV
jan 25 13:08:32 marcos-laptop systemd[1862]: onedrive.service: Unit entered failed state.
jan 25 13:08:32 marcos-laptop systemd[1862]: onedrive.service: Failed with result 'core-dump'.
jan 25 13:24:23 marcos-laptop systemd[1862]: Started OneDrive Free Client.
jan 25 13:24:27 marcos-laptop onedrive[4294]: Downloading: ./Apartamentos/Parque Laranjeiras - Pinheiro Machado 22-Bl3-310/IPTU/1485356674692.jpg
jan 25 13:24:28 marcos-laptop onedrive[4294]: Uploading: ./Apartamentos/Parque Laranjeiras - Pinheiro Machado 22-Bl3-310/IPTU/IPTU 2017 - Pq Laranjeiras - Comprovante de Pagto.jpg
jan 25 13:25:37 marcos-laptop onedrive[4294]: Deleting remote item: ./Apartamentos/Parque Laranjeiras - Pinheiro Machado 22-Bl3-310/IPTU/1485356674692.jpg

**Comment by skilion** [comment] 2018-01-10 13:57
Duplicate of #79

**Closed by skilion** 2018-01-10 13:57 UTC
