### ISSUE TITLE
[Exception] Couldn't resolve host name on handle <xyz>

### ISSUE THREAD

**Issue by sidhant** [skilion/onedrive#132] opened 2016-12-15 18:14 UTC
Seeing this repeatedly when I leave Onedrive client syncing overnight.

`std.net.curl.CurlException@std/net/curl.d(4042): Couldn't resolve host name on handle 210F930
----------------
??:? pure @safe void std.exception.bailOut!(std.net.curl.CurlException).bailOut(immutable(char)[], ulong, const(char[])) [0x5f89fd]
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x5f8979]
??:? void std.net.curl.Curl._check(int) [0x5d7066]
??:? int std.net.curl.Curl.perform(std.typecons.Flag!("throwOnError").Flag) [0x5d74a0]
??:? int std.net.curl.HTTP.perform(std.typecons.Flag!("throwOnError").Flag) [0x5d425f]
??:? void onedrive.OneDriveApi.download(const(char)[], immutable(char)[]) [0x593777]
??:? void onedrive.OneDriveApi.downloadById(const(char)[], immutable(char)[]) [0x59159c]
??:? void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x59cba6]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x59c550]
??:? void sync.SyncEngine.applyDifferences() [0x59b6d0]
??:? void main.performSync(sync.SyncEngine) [0x58ba4b]
??:? _Dmain [0x58b28e]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5a8ade]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a8a28]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5a8a9a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a8a28]
??:? _d_run_main [0x5a8999]
??:? main [0x58ea95]
??:? __libc_start_main [0xdeb4482f]`

**Comment by thomasfedb** [comment] 2017-04-02 05:24
I've seen this also. File seems to download fine once the daemon is restarted (which I've configured to happen automatically when it crashes...).

**Comment by abraunegg** [comment] 2018-04-24 02:11
@sidhant 
This issue is caused by slow local / Internet DNS resolution & the default D internal value being too low. The fix for this is to change the DNS timeout to 5 seconds for the HTTP properties are set. I have updated #314 to include this fix. Since making this change I have not seen this issue again.

There are 2 ways to get the latest code:

Option 1:
```
git clone https://github.com/skilion/onedrive.git
git fetch origin pull/314/head:pr314
git checkout pr314
make
make install
```

Option 2:

```
git clone https://github.com/abraunegg/onedrive.git
make
make install
```

**Comment by abraunegg** [comment] 2018-05-06 20:14
@sidhant 
Any update on this issue?

**Comment by abraunegg** [comment] 2018-05-26 03:01
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive

**Comment by abraunegg** [comment] 2018-05-27 19:37
As you opened the issue you need to close it - I cannot do that.

**Closed** 2018-05-28 18:17 UTC
