### ISSUE TITLE
Client crashes during upload, status code 412

### ISSUE THREAD

**Issue by andystevens91** [skilion/onedrive#296] opened 2018-02-17 23:54 UTC
Hi. I've been using this client for some time and it works reasonably well, but now I'm trying to upload a folder with thousands of subfolders, and everytime I start the daemon (I run in in service mode using sysctl) it crashes 5 minutes later. Here is the log:

> feb 18 00:39:12 andrea-N240JU onedrive[29970]: Uploading file ./Università/Magistrale/2° anno - Primo semestre/Machine Learning/Ponedrive.OneDriveException@src/onedrive.d(408): HTTP request returned status code 412 (Precondition Failed)
> feb 18 00:39:12 andrea-N240JU onedrive[29970]: {
> feb 18 00:39:12 andrea-N240JU onedrive[29970]:     "error": {
> feb 18 00:39:12 andrea-N240JU onedrive[29970]:         "code": "resourceModified",
> feb 18 00:39:12 andrea-N240JU onedrive[29970]:         "innerError": {
> feb 18 00:39:12 andrea-N240JU onedrive[29970]:             "date": "2018-02-17T23:39:14",
> feb 18 00:39:12 andrea-N240JU onedrive[29970]:             "request-id": "0128d167-2b89-44ea-912a-ba1fb487363b"
> feb 18 00:39:12 andrea-N240JU onedrive[29970]:         },
> feb 18 00:39:12 andrea-N240JU onedrive[29970]:         "message": "ETag does not match current item's value"
> feb 18 00:39:12 andrea-N240JU onedrive[29970]:     }
> feb 18 00:39:12 andrea-N240JU onedrive[29970]: }
> feb 18 00:39:12 andrea-N240JU onedrive[29970]: ----------------
> feb 18 00:39:12 andrea-N240JU onedrive[29970]: ??:? void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x277da304]
> feb 18 00:39:12 andrea-N240JU onedrive[29970]: ??:? std.json.JSONValue onedrive.OneDriveApi.patch!(char).patch(const(char)[], const(char)[]) [0x277da3ca]
> feb 18 00:39:12 andrea-N240JU onedrive[29970]: ??:? std.json.JSONValue onedrive.OneDriveApi.updateById(const(char)[], const(char)[], std.json.JSONValue, const(char)[]) [0x277d8de3]
> feb 18 00:39:12 andrea-N240JU onedrive[29970]: ??:? void sync.SyncEngine.uploadLastModifiedTime(const(char)[], const(char)[], const(char)[], std.datetime.systime.SysTime) [0x277e3d13]
> feb 18 00:39:12 andrea-N240JU onedrive[29970]: ??:? void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x277e3a4c]
> feb 18 00:39:12 andrea-N240JU onedrive[29970]: ??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x277e34c8]
> feb 18 00:39:12 andrea-N240JU onedrive[29970]: ??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x277e33eb]
> feb 18 00:39:12 andrea-N240JU onedrive[29970]: ??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x277e33eb]
> feb 18 00:39:12 andrea-N240JU onedrive[29970]: ??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x277e33eb]
> feb 18 00:39:12 andrea-N240JU onedrive[29970]: ??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x277e33eb]
> feb 18 00:39:12 andrea-N240JU systemd[1724]: onedrive.service: Main process exited, code=exited, status=1/FAILURE
> feb 18 00:39:12 andrea-N240JU systemd[1724]: onedrive.service: Unit entered failed state.
> feb 18 00:39:12 andrea-N240JU systemd[1724]: onedrive.service: Failed with result 'exit-code'.
> 

I'm using Ubuntu 17.10 and onedrive v1.1.1.

**Comment by andystevens91** [comment] 2018-02-18 00:06
Sometimes inside the logs status code 412 happens without a crash, just printing this:

> feb 18 01:04:26 andrea-N240JU onedrive[30824]: HTTP request returned status code 412 (Precondition Failed)
> feb 18 01:04:26 andrea-N240JU onedrive[30824]: {
> feb 18 01:04:26 andrea-N240JU onedrive[30824]:     "error": {
> feb 18 01:04:26 andrea-N240JU onedrive[30824]:         "code": "resourceModified",
> feb 18 01:04:26 andrea-N240JU onedrive[30824]:         "innerError": {
> feb 18 01:04:26 andrea-N240JU onedrive[30824]:             "date": "2018-02-18T00:03:47",
> feb 18 01:04:26 andrea-N240JU onedrive[30824]:             "request-id": "542ce81e-36e4-4ba6-917c-560e9998700f"
> feb 18 01:04:26 andrea-N240JU onedrive[30824]:         },
> feb 18 01:04:26 andrea-N240JU onedrive[30824]:         "message": "ETag does not match current item's value"
> feb 18 01:04:26 andrea-N240JU onedrive[30824]:     }
> feb 18 01:04:26 andrea-N240JU onedrive[30824]: }
>

**Comment by skilion** [comment] 2018-02-18 13:47
Can you share the files that cause those errors?

**Comment by andystevens91** [comment] 2018-02-18 16:20
They are just pictures from the Labeled Faces in the Wild dataset (http://vis-www.cs.umass.edu/lfw/), that I used for a University project, for example this one (after I restart the client the picture gets uploaded, but another one will cause a crash soon).

![george_w_bush_0384](https://user-images.githubusercontent.com/5349963/36354130-df43a2d0-14cf-11e8-95da-14ef28d8d3c6.jpg)

**Comment by skilion** [comment] 2018-02-18 21:55
I have thoroughly debugged the issue (which has been reported since this app was made public on github) and I have concluded that the issue is caused by OneDrive as the code follows the API guidelines.

You can follow the issue on the OneDrive official repository https://github.com/OneDrive/onedrive-api-docs/issues/800

**Comment by abraunegg** [comment] 2018-04-23 09:59
@andystevens91 

Any update? Have you tried using #314 where there a number of fixes including 412 errors.

**Comment by abraunegg** [comment] 2018-05-04 10:02
@andystevens91
Given it is all working - can we close this case now as it is resolved?

**Closed** 2018-05-04 10:35 UTC
