### ISSUE TITLE
Error Key not found: id when start the app after unshare a folder

### ISSUE THREAD

**Issue by ppadial** [skilion/onedrive#428] opened 2018-10-31 01:37 UTC
Hi,

the tool was working perfect, but after I unshare a folder with the synced account i got this error everytime i start the app. Even if i delete everything and start from scratch (deleting the API Token, OneDrive folder and ./config/onedrive folder.

```Oct 31 02:34:39 my systemd[2968]: Started OneDrive Free Client.
Oct 31 02:34:45 my onedrive[27601]: Key not found: id
Oct 31 02:34:47 my onedrive[27601]: Key not found: id
Oct 31 02:34:49 my onedrive[27601]: std.json.JSONException@std/json.d(494): Key not found: id
Oct 31 02:34:49 my onedrive[27601]: ----------------
Oct 31 02:34:49 my onedrive[27601]: ??:? pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, const(char[])) [0xae0ef6d3]
Oct 31 02:34:49 my onedrive[27601]: ??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException).enforce!(inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0xae178372]
Oct 31 02:34:49 my onedrive[27601]: ??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0xae130a25]
Oct 31 02:34:49 my onedrive[27601]: ??:? itemdb.Item sync.makeItem(ref const(std.json.JSONValue)) [0xae106ff3]
Oct 31 02:34:49 my onedrive[27601]: ??:? void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0xae107cd6]
Oct 31 02:34:49 my onedrive[27601]: ??:? void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0xae107b47]
Oct 31 02:34:49 my onedrive[27601]: ??:? void sync.SyncEngine.applyDifferences() [0xae107893]
Oct 31 02:34:49 my onedrive[27601]: ??:? void main.performSync(sync.SyncEngine) [0xae0f6933]
Oct 31 02:34:49 my onedrive[27601]: ??:? _Dmain [0xae0f6497]
```

Added debug output:

```
user@host:~/$ onedrive --verbose
Loading config ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/user/OneDrive
Initializing the Synchronization Engine ...
Applying changes of 9D7667C927570D06!101
Processing 9D7667C927570D06!101 root
Root
Processing 9D7667C927570D06!103 Pictures
Folder
Creating directory Pictures
Processing 9D7667C927570D06!104 Documents
Folder
Creating directory Documents
Processing 9D7667C927570D06!102 Getting started with OneDrive.pdf
File
Downloading Getting started with OneDrive.pdf... done.
Processing 9D7667C927570D06!121 backup_delegated_account
Remote item
Creating directory backup_delegated_account
Processing 9D7667C927570D06!130 OneNote
Remote item
Creating directory OneNote
Processing 9D7667C927570D06!129 IT
Remote item
Creating directory IT
Processing 9D7667C927570D06!142 a
File
Downloading a... done.
Processing 9D7667C927570D06!101 root
Root
Applying changes of 27CF47E2358920D5!67093
Key not found: id
Applying changes of 9D7667C927570D06!101
Applying changes of 27CF47E2358920D5!67093
Key not found: id
Applying changes of 9D7667C927570D06!101
Applying changes of 27CF47E2358920D5!67093
std.json.JSONException@std/json.d(494): Key not found: id
----------------
??:? pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, const(char[])) [0xc29976d3]
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException).enforce!(inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0xc2a20372]
??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0xc29d8a25]
??:? itemdb.Item sync.makeItem(ref const(std.json.JSONValue)) [0xc29aeff3]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0xc29afcd6]
??:? void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0xc29afb47]
??:? void sync.SyncEngine.applyDifferences() [0xc29af893]
??:? void main.performSync(sync.SyncEngine) [0xc299e933]
??:? _Dmain [0xc299e497]
```

**Comment by abraunegg** [comment] 2018-10-31 07:13
Hi,

Your specific issue is caused by a OneDrive API change and has been resolved in my branch / repository. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by abraunegg** [comment] 2018-10-31 10:34
@ppadial

No - that is not normal - as that works. Did you follow the upgrade instructions - removing the items database

**Comment by ppadial** [comment] 2018-10-31 10:35
yes, i basically made a clean start and didnt work, i will check again and let you know, give 4 minutes

**Comment by ppadial** [comment] 2018-10-31 10:39
```
Oct 31 11:36:46 luciernaga onedrive[2594]: Initializing the Synchronization Engine ...
Oct 31 11:36:49 luciernaga onedrive[2594]: Initializing monitor ...
Oct 31 11:36:49 luciernaga onedrive[2594]: OneDrive monitor interval (seconds): 45
Oct 31 11:37:34 luciernaga onedrive[2594]: Syncing changes from OneDrive ...
Oct 31 11:37:36 luciernaga onedrive[2594]: Creating directory: Pictures
Oct 31 11:37:36 luciernaga onedrive[2594]: Creating directory: Documents
Oct 31 11:37:38 luciernaga onedrive[2594]: Downloading file Getting started with OneDrive.pdf ... done.
Oct 31 11:37:38 luciernaga onedrive[2594]: Creating directory: backup_delegated_account
Oct 31 11:37:38 luciernaga onedrive[2594]: Creating directory: OneNote
Oct 31 11:37:38 luciernaga onedrive[2594]: Creating directory: IT
Oct 31 11:37:39 luciernaga onedrive[2594]: Downloading file a ... done.
```

Yes, it download the files at the root level, and creates the folders but doesn't download the folders content.

**Comment by ppadial** [comment] 2018-11-01 10:59
I installed it using the instructions provided (using snap). BTW, you mention before that this is related to a change in Onedrive which hasn't been implemented here yet. So, why close it?

**Closed** 2020-10-27 17:34 UTC
