### ISSUE TITLE
Onedrive crashes with segfault

### ISSUE THREAD

**Issue by CaptainMegane** [skilion/onedrive#89] opened 2016-08-21 06:57 UTC
Hello folks,

first a great job, you did. Thank you for that
But I currently found a very annoying bug, when I try to sync huge data.

Trace says:

Uploading: ./Bild_Archiv/Bild_2007/29.09.  Feier bei Sabine/IMAGE_697.jpg
## sync.SyncException@src/sync.d(350): HTTP request returned status code 412 (Precondition Failed)

??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x59dc73]
??:? void main.performSync(sync.SyncEngine) [0x58bfbe]
??:? _Dmain [0x58b7ee]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5a903e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a8f88]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])_).runAll() [0x5a8ffa]
??:? void rt.dmain2._d_run_main(int, char__, extern (C) int function(char[][])_).tryExec(scope void delegate()) [0x5a8f88]
??:? _d_run_main [0x5a8ef9]
??:? main [0x58eff5]
??:? __libc_start_main [0xea67b44]
## onedrive.OneDriveException@src/onedrive.d(348): HTTP request returned status code 412 (Precondition Failed)

??:? std.json.JSONValue onedrive.OneDriveApi.patch!(char).patch(const(char)[], const(char)[]) [0x5971d5]
??:? void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x5a08a6]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59fc34]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59fa6d]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59fa6d]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59fa6d]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59fa6d]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x59db75]
??:? void main.performSync(sync.SyncEngine) [0x58bfbe]
??:? _Dmain [0x58b7ee]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5a903e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a8f88]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])_).runAll() [0x5a8ffa]
??:? void rt.dmain2._d_run_main(int, char__, extern (C) int function(char[][])_).tryExec(scope void delegate()) [0x5a8f88]
??:? _d_run_main [0x5a8ef9]
??:? main [0x58eff5]
??:? __libc_start_main [0xea67b44]
Segmentation fault
Server 'onedrive' crashed with exit code 139. 

This happens very often mostly after about only 20-50 uploaded files.
After that I have to restart the onedrive-program, what I do with a script for unattended working (i did not install it as service).

After restarting onedrive client it takes a long time until upload continues because the engine first has to check for any changes of existing files.
It would be better - in my mind - first to upload new files and then check for any differences. Maybe it will be good to provide a option that tells the client not to check for differences at start but first upload all locally new files. That would speed up the first-time sync if the client crashed before.

Thanks a lot for you work so far.

BR

Marcus

**Comment by CaptainMegane** [comment] 2016-08-21 07:43
This bug is reported severall times. I think it related to uploading pictutes aß IT does Not occur other files.

**Comment by HeronSantosCom** [comment] 2016-08-31 00:38
I'm facing the same problem.
Certain file types, randomly, invokes this error.
I always have to restart the process.
Follows the dump of the error:

> Ago 29 23:57:08 htpc-desktop onedrive[8415]: sync.SyncException@src/sync.d(350): HTTP request returned status code 412 (Precondition Failed)
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ----------------
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x59d713]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? void main.performSync(sync.SyncEngine) [0x58ba5e]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? _Dmain [0x58b28e]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5a8ade]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a8a28]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5a8a9a]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a8a28]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? _d_run_main [0x5a8999]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? main [0x58ea95]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? __libc_start_main [0x61efc82f]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: onedrive.OneDriveException@src/onedrive.d(348): HTTP request returned status code 412 (Precondition Failed)
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ----------------
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? std.json.JSONValue onedrive.OneDriveApi.patch!(char).patch(const(char)[], const(char)[]) [0x596c75]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x5a0346]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59f6d4]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59f50d]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59f50d]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59f50d]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x59d615]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? void main.performSync(sync.SyncEngine) [0x58ba5e]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? _Dmain [0x58b28e]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5a8ade]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a8a28]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5a8a9a]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a8a28]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? _d_run_main [0x5a8999]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? main [0x58ea95]
Ago 29 23:57:08 htpc-desktop onedrive[8415]: ??:? __libc_start_main [0x61efc82f]
Ago 29 23:57:08 htpc-desktop systemd[3534]: onedrive.service: Main process exited, code=killed, status=11/SEGV
Ago 29 23:57:08 htpc-desktop systemd[3534]: onedrive.service: Unit entered failed state.
Ago 29 23:57:08 htpc-desktop systemd[3534]: onedrive.service: Failed with result 'signal'.

**Comment by abraunegg** [comment] 2016-09-20 21:44
With this error, it is all about OneDrive returning inconsistent data back to the OneDrive Client. in #82, what I have done is perform additional validation around the response from OneDrive and perform the query / upload again.

When testing - generally this works - however at times, the 410 / 412 generates a further 415 error, which then gets gracefully handled, and the file get's successfully uploaded the next time the client is run

**Comment by vasuarv** [comment] 2016-10-02 00:55
I am seeing a slightly different error http error code (416) below, and that seems very reproducible.

Continuing the upload session ...
**onedrive.OneDriveException@src/onedrive.d(348): HTTP request returned status code 416 (Requested Range Not Satisfiable)**
----------------
??:? std.json.JSONValue onedrive.OneDriveApi.uploadFragment(const(char)[], immutable(char)[], long, long, long) [0x592ee1]
??:? std.json.JSONValue upload.UploadSession.upload() [0x5a2d19]
??:? void sync.SyncEngine.init() [0x59be6a]
??:? _Dmain [0x58bdc0]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5a966e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a95b8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5a962a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a95b8]
??:? _d_run_main [0x5a9529]
??:? main [0x58f5d5]
??:? __libc_start_main [0x7aceb82f]
Segmentation fault (core dumped)

**Comment by studio404pl** [comment] 2016-11-05 16:07
i've solved the problem by renaming file. i had `:` sign. Maybe that error is related to wrong url encoding when it comes to passing names or creating requests.

**Comment by xcffl** [comment] 2017-06-14 17:32
I have a quite similar problem. But I don't have any file with filename having a `:` sign. It seems like that it crushed after syncing these files:
```
EA2C9F28B34278CF!57471 Cur_HorizontalText_1_1.png
The item is already present
EA2C9F28B34278CF!57470 Cur_HorizontalText_1_1@2x.png
The item is already present
```

And the error output is here:
```
Timeout was reached on handle 557EF706CF70
Timeout was reached on handle 557EF706CF70
sync.SyncException@src/sync.d(176): Timeout was reached on handle 557EF706CF70
----------------
??:? void sync.SyncEngine.applyDifferences() [0xf5240453]
??:? void main.performSync(sync.SyncEngine) [0xf522e627]
??:? _Dmain [0xf522de48]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0xf525795b]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xf525788b]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0xf5257904]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xf525788b]
??:? _d_run_main [0xf52577fb]
??:? main [0xf5232003]
??:? __libc_start_main [0x753dd3f0]
onedrive.OneDriveException@src/onedrive.d(375): Timeout was reached on handle 557EF706CF70
----------------
??:? std.json.JSONValue onedrive.OneDriveApi.perform() [0xf52377b1]
??:? std.json.JSONValue onedrive.OneDriveApi.get(const(char)[], bool) [0xf5235ffa]
??:? std.json.JSONValue onedrive.OneDriveApi.viewChangesByPath(const(char)[], const(char)[]) [0xf52340d6]
??:? void sync.SyncEngine.applyDifferences() [0xf524002e]
??:? void main.performSync(sync.SyncEngine) [0xf522e627]
??:? _Dmain [0xf522de48]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0xf525795b]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xf525788b]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0xf5257904]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xf525788b]
??:? _d_run_main [0xf52577fb]
??:? main [0xf5232003]
??:? __libc_start_main [0x753dd3f0]
std.net.curl.CurlTimeoutException@std/net/curl.d(4308): Timeout was reached on handle 557EF706CF70
----------------
??:? pure @safe void std.exception.bailOut!(std.net.curl.CurlTimeoutException).bailOut(immutable(char)[], ulong, const(char[])) [0xf52b9f78]
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlTimeoutException, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0xf52b9eed]
??:? void std.net.curl.Curl._check(int) [0xf528eee9]
??:? int std.net.curl.Curl.perform(std.typecons.Flag!("throwOnError").Flag) [0xf528f34c]
??:? int std.net.curl.HTTP.perform(std.typecons.Flag!("throwOnError").Flag) [0xf528c017]
??:? std.json.JSONValue onedrive.OneDriveApi.perform() [0xf5237746]
??:? std.json.JSONValue onedrive.OneDriveApi.get(const(char)[], bool) [0xf5235ffa]
??:? std.json.JSONValue onedrive.OneDriveApi.viewChangesByPath(const(char)[], const(char)[]) [0xf52340d6]
??:? void sync.SyncEngine.applyDifferences() [0xf524002e]
??:? void main.performSync(sync.SyncEngine) [0xf522e627]
??:? _Dmain [0xf522de48]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0xf525795b]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xf525788b]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0xf5257904]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xf525788b]
??:? _d_run_main [0xf52577fb]
??:? main [0xf5232003]
??:? __libc_start_main [0x753dd3f0]
[1]    11839 segmentation fault (core dumped)  onedrive --resync
```

**Comment by ibrokemypie** [comment] 2017-07-06 08:58
```
2374F7E55D3E5741!64297 origin
The item has not changed
2374F7E55D3E5741!111088 master
The item is already present
2374F7E55D3E5741!111118 cm-13.0
The item is already present
sync.SyncException@src/sync.d(182): Timeout was reached on handle 14A0950
----------------
??:? void sync.SyncEngine.applyDifferences() [0x5d5d51]
??:? void main.performSync(sync.SyncEngine) [0x5c4b8b]
??:? _Dmain [0x5c4404]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0x5eb976]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5eb8c0]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5eb932]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5eb8c0]
??:? _d_run_main [0x5eb83e]
??:? main [0x5c82ad]
??:? __libc_start_main [0xd1801510]
onedrive.OneDriveException@src/onedrive.d(380): Timeout was reached on handle 14A0950
----------------
??:? std.json.JSONValue onedrive.OneDriveApi.perform() [0x5cd2cb]
??:? std.json.JSONValue onedrive.OneDriveApi.get(const(char)[], bool) [0x5cbb72]
??:? std.json.JSONValue onedrive.OneDriveApi.viewChangesByPath(const(char)[], const(char)[]) [0x5ca06c]
??:? void sync.SyncEngine.applyDifferences() [0x5d593c]
??:? void main.performSync(sync.SyncEngine) [0x5c4b8b]
??:? _Dmain [0x5c4404]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0x5eb976]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5eb8c0]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5eb932]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5eb8c0]
??:? _d_run_main [0x5eb83e]
??:? main [0x5c82ad]
??:? __libc_start_main [0xd1801510]
std.net.curl.CurlTimeoutException@std/net/curl.d(4308): Timeout was reached on handle 14A0950
----------------
??:? pure @safe void std.exception.bailOut!(std.net.curl.CurlTimeoutException).bailOut(immutable(char)[], ulong, const(char[])) [0x650fa0]
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlTimeoutException, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x650f19]
??:? void std.net.curl.Curl._check(int) [0x624c4d]
??:? int std.net.curl.Curl.perform(std.typecons.Flag!("throwOnError").Flag) [0x625098]
??:? int std.net.curl.HTTP.perform(std.typecons.Flag!("throwOnError").Flag) [0x621e77]
??:? std.json.JSONValue onedrive.OneDriveApi.perform() [0x5cd264]
??:? std.json.JSONValue onedrive.OneDriveApi.get(const(char)[], bool) [0x5cbb72]
??:? std.json.JSONValue onedrive.OneDriveApi.viewChangesByPath(const(char)[], const(char)[]) [0x5ca06c]
??:? void sync.SyncEngine.applyDifferences() [0x5d593c]
??:? void main.performSync(sync.SyncEngine) [0x5c4b8b]
??:? _Dmain [0x5c4404]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0x5eb976]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5eb8c0]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5eb932]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5eb8c0]
??:? _d_run_main [0x5eb83e]
??:? main [0x5c82ad]
??:? __libc_start_main [0xd1801510]
zsh: segmentation fault  onedrive -v --resync

```

**Comment by skilion** [comment] 2018-01-10 12:04
Duplicate of #18

**Closed by skilion** 2018-01-10 12:04 UTC
