### ISSUE TITLE
Crash on Sync, error HTTP 412

### ISSUE THREAD

**Issue by lamarios** [skilion/onedrive#40] opened 2016-03-05 00:47 UTC
Hi,
 I'm having an issue where the synchronisation would crash randomly with an error 412. It might be my connection problem, if it's the case it would be good to have an auto retry mechanism in case of http error so I can leave onedrive run in the background until it's really done. 

Internet in my country is having some issues recently so it might be related, the cable from Singapore to US is broken and will be fixed at the end of the month so connections to US are very unstable.

Here's the crash log
`Uploading: ./Pictures/htpc/2009-05 France/IMG_0055 copy.JPG
## sync.SyncException@src/sync.d(352): HTTP request returned status code 412 (Precondition Failed)

??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x5cd919]
??:? void main.performSync(sync.SyncEngine) [0x5bdc82]
??:? _Dmain [0x5bd512]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5d8bda]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d8b18]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])_).runAll() [0x5d8b96]
??:? void rt.dmain2._d_run_main(int, char__, extern (C) int function(char[][])_).tryExec(scope void delegate()) [0x5d8b18]
??:? _d_run_main [0x5d8a75]
??:? main [0x5bf96d]
??:? __libc_start_main [0xb397ea3f]
## onedrive.OneDriveException@src/onedrive.d(337): HTTP request returned status code 412 (Precondition Failed)

??:? void onedrive.OneDriveApi.checkHttpCode() [0x5c4f20]
??:? std.json.JSONValue onedrive.OneDriveApi.patch!(char).patch(const(char)[], const(char)[]) [0x5c75ab]
??:? void sync.SyncEngine.uploadLastModifiedTime(const(char)[], const(char)[], std.datetime.SysTime) [0x5d0561]
??:? void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x5cfde0]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5cf2bc]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5cf0da]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5cf0da]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5cf0da]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5cf0da]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x5cd818]
??:? void main.performSync(sync.SyncEngine) [0x5bdc82]
??:? _Dmain [0x5bd512]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5d8bda]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d8b18]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])_).runAll() [0x5d8b96]
??:? void rt.dmain2._d_run_main(int, char__, extern (C) int function(char[][])_).tryExec(scope void delegate()) [0x5d8b18]
??:? _d_run_main [0x5d8a75]
??:? main [0x5bf96d]
??:? __libc_start_main [0xb397ea3f]`

**Comment by jlcs-es** [comment] 2016-03-05 22:40
It looks like a not treated error code from the Onedrive API:
https://github.com/OneDrive/onedrive-api-docs/blob/master/misc/errors.md

Would be great if you follow back the trace and post in which function you think the error is.

**Comment by cdiscrete** [comment] 2016-03-17 14:33
Exactly the same problem here. Consider simply retrying?

**Comment by lamarios** [comment] 2016-03-18 01:45
It crashes after uploading 100mb or so. I need to upload 300 GB of backups so i'm not considering retrying.

**Comment by cdiscrete** [comment] 2016-03-18 06:21
Me too. I ended up with seting up a cron job and reboot onedrive every two minutes.

A super dirty hack but it works :)

**Comment by thomasfedb** [comment] 2018-01-29 01:32
@lamarios does this issue occur with the latest codebase? If not, could you close this issue please.

**Comment by lamarios** [comment] 2018-01-29 01:35
Hi,

Sorry. I’ve been using rclone since then, no chance to check out the new code base.

**Comment by thomasfedb** [comment] 2018-01-29 01:36
@lamarios might be best to close the issue then, given that you can't reproduce on latest codebase.

**Closed** 2018-01-29 01:54 UTC
