### ISSUE TITLE
src/sqlite.d(71): Error: module `stdlib` is in file 'std/c/stdlib.d' which cannot be read - compile error with dmd 2.081.1

### ISSUE THREAD

**Issue by ptrb78** [skilion/onedrive#392] opened 2018-07-11 14:45 UTC
make
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
src/sqlite.d(71): Error: module `stdlib` is in file 'std/c/stdlib.d' which cannot be read
import path[0] = /usr/include/dmd/phobos
import path[1] = /usr/include/dmd/druntime/import
Makefile:29: recipe for target 'onedrive' failed
make: *** [onedrive] Error 1

**Comment by fiercebrake** [comment] 2018-07-11 17:02
[fierce@aster onedrive]$ make
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
src/sqlite.d(71): Error: module `core.stdc.stdlib` from file /usr/include/dmd/phobos/std/c/stdlib.d conflicts with another module stdlib from file /usr/include/dmd/druntime/import/core/stdc/stdlib.d
make: *** [Makefile:29: onedrive] Error 1
[fierce@aster onedrive]$ 

Using 

http://downloads.dlang.org/releases/2.x/2.081.1/dmd-2.081.1-0.fedora.x86_64.rpm

**Comment by abraunegg** [comment] 2018-07-11 19:21
Hi,

Your specific issue has been resolved in my branch / repository. The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests may not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by fiercebrake** [comment] 2018-07-11 20:07
awesome!

Yes it works. Thanks for your work!

**Comment by EvilJimJafar** [comment] 2018-07-26 08:24
Getting this from the aur/onedrive-git package too:

```
make: Entering directory '/home/jim/.cache/aurman/onedrive-git/src/onedrive'
echo v1.1.1-2-gc231b13 >version
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
src/sqlite.d(71): Error: module `stdlib` is in file 'std/c/stdlib.d' which cannot be read
import path[0] = /usr/include/dlang/dmd
make: *** [Makefile:29: onedrive] Error 1
make: Leaving directory '/home/jim/.cache/aurman/onedrive-git/src/onedrive'
==> ERROR: A failure occurred in build().
    Aborting...
2018-07-26 16:22:35,890 - wrappers - makepkg - ERROR - makepkg query ['makepkg', '-cf', '--noconfirm'] failed in directory /home/jim/.cache/aurman/onedrive-git
```

**Comment by abraunegg** [comment] 2018-07-26 09:01
@EvilJimJafar 
Yep - this is because the maintainer of the AUR packages wont migrate to using a newer branch of code as this one is not being maintained. 

You are best cloning from here: https://github.com/abraunegg/onedrive & not using the AUR packages due to the defects it contains, or complain to the AUR package maintainer.

**Comment by EvilJimJafar** [comment] 2018-07-26 09:10
@abraunegg Thanks - I've already added a comment to the package suggesting a switch to your repo and linking to this discussion.

**Comment by abraunegg** [comment] 2018-07-26 09:14
No worries - I suggested that a while back. It seems the current AUR maintainer would rather stick with the skilion branch for the time being.

**Comment by escrowdis** [comment] 2018-08-14 15:37
It's caused by the library import path has been revised. So I fixed it by changing 'src/sqlite.d' line 71:
from `import std.c.stdlib: atoi;` to `import core.stdc.stdlib: atoi;`

**Comment by johnDotSlash** [comment] 2018-08-19 12:56
Thank you abraunegg your forked version has worked just fine on my linux Mint 18 system. No I can do some work for work ... ;-(
j./

**Comment by skilion** [comment] 2018-09-09 13:35
Fixed in 19793c854d9dd97eb5accf94d21406f825c75fb5

**Closed by skilion** 2018-09-09 13:35 UTC

**Comment by rillaxy** [comment] 2019-09-16 06:47
> make
> dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
> src/sqlite.d(71): Error: module `stdlib` is in file 'std/c/stdlib.d' which cannot be read
> import path[0] = /usr/include/dmd/phobos
> import path[1] = /usr/include/dmd/druntime/import
> Makefile:29: recipe for target 'onedrive' failed
> make: *** [onedrive] Error 1

Hi , I am getting the same error with you. How do you solve this problem ?
Looking forward to hearing from you . Thank you very much.
Rilla

**Comment by abraunegg** [comment] 2019-09-16 07:29
@rillaxy

The 'skilion' repo appears to have been abandoned and contains many other issues that have not been fixed. It contains functional defects that put you at risk of data loss and corruption if you use this repo. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive
