### ISSUE TITLE
HTTP request returned status code 500 (Internal Server Error)

### ISSUE THREAD

**Issue by constant5** [skilion/onedrive#303] opened 2018-02-25 15:24 UTC
After a system resume I get the error below.  The problem is fixed if If I logout of onedrive and then log back in with a new uri.  Help!

HTTP request returned status code 500 (Internal Server Error)
{
    "error": {
        "code": "InternalServerError",
        "innerError": {
            "date": "2018-02-25T15:15:13",
            "request-id": "f9e7035c-3086-4502-9a34-b6e8eb62eca1"
        },
        "message": "nextLink value without skip or skiptoken"
    }
}
HTTP request returned status code 500 (Internal Server Error)
{
    "error": {
        "code": "InternalServerError",
        "innerError": {
            "date": "2018-02-25T15:15:14",
            "request-id": "7a0a807d-fb07-43f9-8e30-5d0cbc8bccea"
        },
        "message": "nextLink value without skip or skiptoken"
    }
}
onedrive.OneDriveException@src/onedrive.d(408): HTTP request returned status code 500 (Internal Server Error)
{
    "error": {
        "code": "InternalServerError",
        "innerError": {
            "date": "2018-02-25T15:15:14",
            "request-id": "9a2f453c-1836-4492-b9dd-77213677c2a2"
        },
        "message": "nextLink value without skip or skiptoken"
    }
}
----------------
src/onedrive.d:33 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x571ef0]
src/onedrive.d:286 std.json.JSONValue onedrive.OneDriveApi.get(const(char)[], bool) [0x5714fe]
src/onedrive.d:111 std.json.JSONValue onedrive.OneDriveApi.viewChangesById(const(char)[], const(char)[], const(char)[]) [0x57032d]
src/sync.d:165 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x578e9b]
src/sync.d:146 void sync.SyncEngine.applyDifferences() [0x578d25]
src/main.d:190 void main.performSync(sync.SyncEngine) [0x5691c7]
src/main.d:118 _Dmain [0x568d24]

**Comment by kaischmerer** [comment] 2018-02-26 09:38
Same error:
HTTP request returned status code 500 (Internal Server Error)
{
    "error": {
        "code": "InternalServerError",
        "innerError": {
            "date": "2018-02-26T09:29:50",
            "request-id": "e92e088d-343a-49d9-8f42-1a023c9bbcf5"
        },
        "message": "nextLink value without skip or skiptoken"
    }
}
HTTP request returned status code 500 (Internal Server Error)
{
    "error": {
        "code": "InternalServerError",
        "innerError": {
            "date": "2018-02-26T09:29:52",
            "request-id": "6cb95bfa-707c-4e2f-8f14-04669df84716"
        },
        "message": "nextLink value without skip or skiptoken"
    }
}
onedrive.OneDriveException@src/onedrive.d(408): HTTP request returned status code 500 (Internal Server Error)
{
    "error": {
        "code": "InternalServerError",
        "innerError": {
            "date": "2018-02-26T09:29:54",
            "request-id": "e36dad43-5187-4fb7-aa74-f978de1689de"
        },
        "message": "nextLink value without skip or skiptoken"
    }
}
----------------
src/onedrive.d:33 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x5d0004]
src/onedrive.d:285 std.json.JSONValue onedrive.OneDriveApi.get(const(char)[], bool) [0x5cf66a]
src/onedrive.d:111 std.json.JSONValue onedrive.OneDriveApi.viewChangesById(const(char)[], const(char)[], const(char)[]) [0x5ce26d]
src/sync.d:165 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x5d744f]
src/sync.d:146 void sync.SyncEngine.applyDifferences() [0x5d72c6]
src/main.d:193 void main.performSync(sync.SyncEngine) [0x5c786f]                                                                                          
src/main.d:121 _Dmain [0x5c73eb]                                                                                                                          
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0x5ea7e3]                                                                          
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5ea713]                          
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5ea78c]                                                
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5ea713]                          
??:? _d_run_main [0x5ea683]                                                                                                                               
??:? main [0x5ccb57]                                                                                                                                      
??:? __libc_start_main [0xae86c82f]
Speicherzugriffsfehler

**Comment by Uniqen** [comment] 2018-02-26 16:20
Same error here, running in docker container.

**Comment by kaischmerer** [comment] 2018-02-27 13:32
Did a resync which seem to solve the problem:
onedrive --monitor --resync --confdir="~/.config/onedriveWork"

**Comment by brantg** [comment] 2018-03-07 14:32
I get this as well but number of changes seems to be a factor.  I delete seven files, it throws the error above but if I delete 1 file, sync, delete 1 file, sync and so on it works without error.  I have not tried the logout/login step yet but I will the next time it manifests.

**Comment by abraunegg** [comment] 2018-03-14 06:58
When I was playing around in 2016 - that gateway security scanning via WCCP / proxy caused OneDrive to send back invalid JSON content which the code didnt handle.

In onedrive.d where the checkHttpCode() parts are - better handling of the actual response is needed here rather than generating an exception.

In #314 I have tried to fix this a little (more work needed on exception handling) - but in the event of a server side issue the code should generally issue a retry.

**Comment by strasky** [comment] 2018-03-27 04:48
I am seeing the same issue but logout/in does not solve it, only resync.

**Comment by brantg** [comment] 2018-03-27 19:15
I agree with @strasky, logout/login made no dent.  Resync is the only solution that works for my setup.

**Comment by abraunegg** [comment] 2018-04-19 06:27
@strasky , @brantg 

Can you retry with using #314 as your version?

I can bulk delete files locally / remotely & perform a sync without issue.

Best regards,

Alex

**Comment by strasky** [comment] 2018-04-20 02:04
I tried #314, I first got an error on make install:

```
> make install
install -D onedrive /usr/local/bin/onedrive
install -D -m 644 onedrive.service /usr/lib/systemd/user/onedrive.service
install -D -m 644 onedrive@.service /usr/lib/systemd/user/onedrive@.service
install: cannot stat 'onedrive@.service': No such file or directory
make: *** [Makefile:27: install] Error 1
```

...but I could see that the binary and service had been installed ok to test.

Next I hit permissions error:

```
> onedrive --resync -v
std.file.FileException@std/file.d(2315): /var/log/onedrive/: Permission denied
----------------
/usr/include/dmd/phobos/std/file.d:227 @safe bool std.file.cenforce!(bool).cenforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x56f5a7]
??:? @safe bool std.file.ensureDirExists!().ensureDirExists(const(char[])) [0x5b4335]
??:? @safe void std.file.mkdirRecurse(const(char[])) [0x5b2cf0]
src/main.d:106 _Dmain [0x5789ea]
```

Created that dir with right permissions. Then I get this:

```
>onedrive --resync -v
Loading config ...
Using Config Dir: /home/strasky/.config/onedrive
No config file found, using defaults
Deleting the saved status ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/strasky/OneDrive
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: b!RrO0cFeIykammlDhje!hXsbItKVR0My1Ik0m6g2Rcz2wp6ROTa9-ERIdRL6xLvSwd
Default Root ID: 01K6QNM3N6Y38FIEJW7725BZO354PWSELRRZ
Remaining Free Space: 1075334045994
Applying changes of Path ID: 01K6QNM3N6Y38FIEJW7725BZO354PWSELRRZ
core.exception.AssertError@src/itemdb.d(293): Assertion failure
----------------
??:? _d_assertp [0x59ef25]
src/itemdb.d:293 immutable(char)[] itemdb.ItemDatabase.computePath(const(char)[], const(char)[]) [0x57663d]
src/sync.d:364 void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0x58fbc6]
src/sync.d:303 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x58f864]
src/sync.d:167 void sync.SyncEngine.applyDifferences() [0x58f0d5]
src/main.d:313 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x579722]
src/main.d:206 _Dmain [0x57910c]
```

**Comment by abraunegg** [comment] 2018-04-20 02:07
Did you remove the items.* from the config directory?

**Comment by abraunegg** [comment] 2018-04-20 08:11
I found the DB assertion issue - fixing at the moment

**Comment by abraunegg** [comment] 2018-04-20 08:45
Commit 66d00c5ec9e00b57e1e237477e9e12c80d46763c should fix the assertion issue.

**Comment by brantg** [comment] 2018-04-20 17:36
I apologize, I'm tracking this but have been unable to test yet as the system in question is busy being used (and I'm using periodic forced --resync calls to get by).  As soon as I can I will try to get that commit into play & report back.

**Comment by abraunegg** [comment] 2018-04-22 21:48
I have a clean 'reproducer' here now.

When I upload a folder that has many items through the OneDrive WebUI, and some of those items get blocked from being uploaded. For example:

* Extract on Windows & upload the folder
* Files such as `.keep`, `00list`, `__init__.py` do not get uploaded. OneDrive presents this error message: `Sorry, OneDrive can't upload empty folders or empty files. Please try again.`

After doing this - and then attempting a sync, I get:

```
HTTP request returned status code 500 (Internal Server Error)
{
    "error": {
        "code": "InternalServerError",
        "innerError": {
            "date": "2018-04-22T21:45:34",
            "request-id": "aa5e4042-794d-4e63-8067-c5e2f9ad0306"
        },
        "message": "nextLink value without skip or skiptoken"
    }
}
```

The only way to resolve thus far is to:

1. Remove the offending folder from OneDrive using Web UI
2. Remove the items.sqlite3
3. Perform a sync

This to me is a OneDrive API issue / bug. As it is reproducible 100% of the time hopefully an answer can be sought from the OneDrive API team.

**Comment by abraunegg** [comment] 2018-04-23 03:34
For reference: https://github.com/OneDrive/onedrive-api-docs/issues/844

**Comment by abraunegg** [comment] 2018-04-23 19:36
This is a OneDrive bug:

https://github.com/OneDrive/onedrive-api-docs/issues/844

**Comment by Uniqen** [comment] 2018-04-23 19:43
ok didn't know that batch delete was related to OneDrive/onedrive-api-docs#844 as well (I wasn't deleting empty files).

**Comment by abraunegg** [comment] 2018-04-23 19:49
The crux of the issue is this: 

> This seems to be an issue with how Graph is interpreting the response from OneDrive for Business when the paging token exceeds a particular size.

So when performing large scale changes (add, move, delete) MS Graph is not handling the response correctly .. hopefully they can find the root cause of that, then the `nextLink value without skip or skiptoken` should automatically resolve itself.

**Comment by abraunegg** [comment] 2018-05-05 23:35
@Uniqen @constant5 
The latest #314 includes a check for this issue so that the application gracefully exits if a 500 error is returned.

Given this is a OneDrive API issue - can we close this issue out now?

**Comment by Uniqen** [comment] 2018-05-07 18:53
Fine by me.

**Comment by abraunegg** [comment] 2018-05-11 20:17
@constant5 
Any update?

**Comment by constant5** [comment] 2018-05-11 22:11
Haven't used it in a while because it was messing up files on my windows
machine.

**Comment by abraunegg** [comment] 2018-05-11 23:32
Please can you close this case then

**Closed** 2018-05-12 02:46 UTC
