### ISSUE TITLE
Error while syncing after some time waiting

### ISSUE THREAD

**Issue by Eneitilyn** [skilion/onedrive#18] opened 2016-01-13 18:18 UTC
Everytime i start the program with root#"onedrive -v -m" and then this error shows up after some time passes http://pastebin.com/3higrhaU
I ran it again without the -m option and  there is this error http://pastebin.com/1VBFXACk
I ran it another time without any options and there is this log http://pastebin.com/96UYNhMX
I also saw couple of errors when i scroll up like this one 
"HTTP request returned status code 412 (Precondition Failed)" 
I am using Puppy Linux 6.0.2 32bit

**Comment by abrakev** [comment] 2017-01-10 00:33
I'm having the same issue:
[](http://pastebin.com/DQn0gs61)
It seems to always happen after a 412 Precondition Failed error...

**Comment by thomasfedb** [comment] 2018-01-29 01:35
@Eneitilyn does this issue occur with the latest codebase? If not, could you close this issue please.

**Comment by skilion** [comment] 2018-02-18 21:59
Closing this as duplicate, the issue is tracked here #296 now

**Closed by skilion** 2018-02-18 21:59 UTC
