### ISSUE TITLE
Gateway timeout

### ISSUE THREAD

**Issue by visioncode** [skilion/onedrive#230] opened 2017-09-02 21:54 UTC
What's going on here? In the past everything worked fine ... i'm using current version 1.0.1 of onedrive.

```
Applying differences ...
HTTP request returned status code 504 (Gateway Timeout)
{
    "error": {
        "code": "UnknownError",
        "innerError": {
            "date": "2017-09-02T21:50:08",
            "request-id": "46618521-2c4c-4dcf-8138-383259b3efbd"
        },
        "message": ""
    }
}
Applying differences ...
sync.SyncException@src/sync.d(182): HTTP request returned status code 504 (Gateway Timeout)
{
    "error": {
        "code": "UnknownError",
        "innerError": {
            "date": "2017-09-02T21:50:28",
            "request-id": "2c5c0548-3e42-4699-8075-6cc7a71ac33d"
        },
        "message": ""
    }
}
----------------
src/sync.d:102 void sync.SyncEngine.applyDifferences() [0x5eedfd]
src/main.d:184 void main.performSync(sync.SyncEngine) [0x5dab97]
src/main.d:114 _Dmain [0x5da3bf]
onedrive.OneDriveException@src/onedrive.d(403): HTTP request returned status code 504 (Gateway Timeout)
{
    "error": {
        "code": "UnknownError",
        "innerError": {
            "date": "2017-09-02T21:50:28",
            "request-id": "2c5c0548-3e42-4699-8075-6cc7a71ac33d"
        },
        "message": ""
    }
}
----------------
src/onedrive.d:38 std.json.JSONValue onedrive.OneDriveApi.get(const(char)[], bool) [0x5e3bb3]
src/onedrive.d:114 std.json.JSONValue onedrive.OneDriveApi.viewChangesByPath(const(char)[], const(char)[]) [0x5e1e8c]
src/sync.d:158 void sync.SyncEngine.applyDifferences() [0x5ee9b4]
src/main.d:184 void main.performSync(sync.SyncEngine) [0x5dab97]
src/main.d:114 _Dmain [0x5da3bf]
[1]    19734 segmentation fault  onedrive -v
```

**Comment by WoosterUK** [comment] 2017-09-04 08:58
I'm seeing this too; same set of errors. It's a bit sporadic, in that I can come back much later and things might have settled down, but when the 504 is firing, it's firing consistently.

**Comment by WoosterUK** [comment] 2017-09-05 13:32
Aaand I spoke too soon. The weird thing is I was able to do a bunch of syncing with OneDrive across my desktop and laptop, but now both installs of onedrive (one on Ubuntu 16.04, the other on Linux Mint 18.1) are playing this game.

**Comment by visioncode** [comment] 2017-09-06 05:44
my installation is not usable anymore with this client :( no sporadic function ... any idea?

**Comment by WoosterUK** [comment] 2017-09-12 16:04
On another thread reporting a seg fault, a backtrace was requested, so I'm posting one here in case it can provoke any enlightenment. https://pastebin.com/tWGxa4Hw

**Comment by visioncode** [comment] 2017-09-14 21:11
@WoosterUK please let me know if you find a solution. I don't think that only we both run into this error?
@skilion ? :)

**Comment by jonare77** [comment] 2017-09-16 18:49
Same problems for me.

**Comment by WoosterUK** [comment] 2017-09-20 19:43
So it has started working again, more or less, for me. We'll see how long this lasts!

But one issue that immediately became apparent, and may or may not be related, is that I had some filenames that were not Windows-friendly; see https://github.com/skilion/onedrive/issues/201. It would be worth trying `find | grep :` at the root of your OneDrive sync folders and fixing any colons you find, just in case.

**Comment by WoosterUK** [comment] 2017-09-21 07:57
And it stops again. I managed to upload everything to OneDrive last night on my Ubuntu machine, but the Linux Mint one this morning is getting consistently 504-ed.

**Comment by WoosterUK** [comment] 2017-09-28 16:25
Just to update that one week on, it is still working fine. I think wiping, checking filenames and then reconfiguring has resolved it for me. Anyone else tried this?

**Comment by visioncode** [comment] 2017-09-28 20:21
@WoosterUK thanks for your update. I noticed your post one week ago and tried the same (just "onedrive --logout"). Since then, it also works fine here ...

**Comment by visioncode** [comment] 2017-09-28 20:21
@WoosterUK thanks for your update. I noticed your post one week ago and tried the same (just "onedrive --logout"). Since then, it also works fine here ...

**Comment by docsmooth** [comment] 2017-10-05 15:45
I think the bigger issue is that the 504 is causing the segfault:

Oct  5 10:39:14 kubuntu10 onedrive[3861]: Moving remote item: ./Process-kubuntu10 -> ./Process
Oct  5 10:39:25 kubuntu10 onedrive[3861]: onedrive.OneDriveException@src/onedrive.d(403): HTTP request returned status code 504 (Gateway Timeout)
Oct  5 10:39:25 kubuntu10 onedrive[3861]: {
Oct  5 10:39:25 kubuntu10 onedrive[3861]:     "error": {
Oct  5 10:39:25 kubuntu10 onedrive[3861]:         "code": "UnknownError",
Oct  5 10:39:25 kubuntu10 onedrive[3861]:         "innerError": {
Oct  5 10:39:25 kubuntu10 onedrive[3861]:             "date": "2017-10-05T15:40:24",
Oct  5 10:39:25 kubuntu10 onedrive[3861]:             "request-id": "7ea7a142-de3b-4e74-8da0-7db2ed967639"
Oct  5 10:39:25 kubuntu10 onedrive[3861]:         },
Oct  5 10:39:25 kubuntu10 onedrive[3861]:         "message": ""
Oct  5 10:39:25 kubuntu10 onedrive[3861]:     }
Oct  5 10:39:25 kubuntu10 onedrive[3861]: }
Oct  5 10:39:25 kubuntu10 onedrive[3861]: ----------------
Oct  5 10:39:25 kubuntu10 onedrive[3861]: ??:? std.json.JSONValue onedrive.OneDriveApi.patch!(char).patch(const(char)[], const(char)[]) [0x760147d3]
Oct  5 10:39:25 kubuntu10 onedrive[3861]: ??:? void sync.SyncEngine.uploadMoveItem(immutable(char)[], immutable(char)[]) [0x76023610]
Oct  5 10:39:25 kubuntu10 onedrive[3861]: ??:? void main.main(immutable(char)[][]).__dgliteral6(immutable(char)[], immutable(char)[]) [0x76009ae7]
Oct  5 10:39:25 kubuntu10 kernel: [ 5175.945869] onedrive[3861]: segfault at 0 ip           (null) sp 00007ffee18353e8 error 14 in onedrive[557a75e09000+318000]
Oct  5 10:39:25 kubuntu10 onedrive[3861]: ??:? void monitor.Monitor.update(bool) [0x76010390]
Oct  5 10:39:25 kubuntu10 onedrive[3861]: ??:? _Dmain [0x7600963d]
Oct  5 10:39:25 kubuntu10 systemd[3358]: onedrive.service: Main process exited, code=dumped, status=11/SEGV
Oct  5 10:39:25 kubuntu10 systemd[3358]: onedrive.service: Unit entered failed state.
Oct  5 10:39:25 kubuntu10 systemd[3358]: onedrive.service: Failed with result 'core-dump'.

**Comment by thomasfedb** [comment] 2018-02-09 04:57
@visioncode can you reproduce this on the latest commit?

**Comment by abraunegg** [comment] 2018-05-03 10:31
Most likely this is also related to #320

**Comment by abraunegg** [comment] 2018-05-06 08:05
@visioncode @WoosterUK 
This is resolved in the latest #314 patch set - can you please test and provide feedback.

**Comment by abraunegg** [comment] 2018-05-26 02:58
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive

**Comment by asnowfix** [comment] 2019-03-04 08:24
I am getting the same-looking error with 1.0.1

```
onedrive.OneDriveException@src/onedrive.d(403): HTTP request returned status code 504 (Gateway Timeout)
{
    "error": {
        "code": "UnknownError",
        "innerError": {
            "date": "2019-03-04T07:24:09",
            "request-id": "70f77e01-24a2-431f-861c-38ee77960778"
        },
        "message": ""
    }
}
----------------
0x5642e2463a9c ???
	???:0
0x5642e24d9c4d ???
	???:0
0x5642e2461c52 ???
	???:0
0x5642e246d39b ???
	???:0
0x5642e245efa1 ???
	???:0
0x5642e2460843 ???
	???:0
0x5642e245ebce ???
	???:0
0x5642e25b28be ???
	???:0
0x5642e25b2a2e ???
	???:0
0x5642e25b2dea ???
	???:0
0x5642e25b2a2e ???
	???:0
0x5642e25b2bc0 ???
	???:0
0x5642e245dea3 ???
	???:0
0x7fd61756db96 __libc_start_main
	???:0
0x5642e2455c99 ???
	???:0
0xffffffffffffffff ???
	???:0
Segmentation fault (core dumped)
```

```
$ onedrive --version
onedrive v1.0.1
```

Is there a way to identify which file is causing the crash?

**Comment by abraunegg** [comment] 2019-03-04 09:53
@asnowfix
Your issue is a known bug and this is fixed in my branch. Your application version is also very old.

Also, the 'skilion' code appears to have been abandoned and contains other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by asnowfix** [comment] 2019-03-08 10:11
Thanks @abraunegg , your brnach indeed fixes that particular issue. I have another one that I wlll report on your repo.

**Closed** 2020-10-26 18:29 UTC
