### ISSUE TITLE
JSON Key not found: name

### ISSUE THREAD

**Issue by jlcs-es** [skilion/onedrive#39] opened 2016-03-04 21:44 UTC
Anytime I exec _onedrive_, even with _--resync_, it fails in the middle of synchronization. 
With verbose it shows that for many directories and files works right, but then this appears:

```
std.json.JSONException@std/json.d(442): Key not found: name
----------------
??:? pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, const(char[])) [0x6391e6]
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException, inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0x63924a]
??:? std.json.JSONValue.opIndexinout(pure ref inout(std.json.JSONValue) function(immutable(char)[])) [0x60ac5a]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x5dd963]
??:? void sync.SyncEngine.applyDifferences() [0x5dd6f1]
??:? void main.performSync(sync.SyncEngine) [0x5cf5a7]
??:? _Dmain [0x5cee4a]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5ea50a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5ea448]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5ea4c6]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5ea448]
??:? _d_run_main [0x5ea3a5]
??:? main [0x5d12a5]
??:? __libc_start_main [0x1b789b04]
```

**Comment by GrouchyGaijin** [comment] 2016-03-04 22:16
See issue# https://github.com/skilion/onedrive/issues/24

**Comment by jlcs-es** [comment] 2016-03-05 08:58
Followying the trace seems the _fix_ should be applied in:
https://github.com/skilion/onedrive/blob/master/src/sync.d#L115
But I haven't found the reason or item that the app receives and has no name tag. The API doc only mentions the c-Tag to be missing if the item is a folder.

**Comment by CBTyrone** [comment] 2016-05-11 02:28
I have a fix for this problem: edit src/sync.d at around line 115 (master, currently) with the following:

string name;

		if(auto ntest = "name" in item) {
		
			name = item["name"].str;
		} else {

			skippedItems ~= id;
			return; // Clearly this isn't working out
		}

**Comment by salimk95** [comment] 2016-10-26 16:57
I tried editing the file around line 115 and adding your code @CBTyrone to test it out since i'm having the same issue but it's still crashing

**Comment by CBTyrone** [comment] 2016-10-26 23:05
@salimk95 you'll need to scratch the assignment of thr name string near 115, and turn it into a plain declaration of name. Then after the line about parentId, you can insert the code. This stops the program from trying to find 'name' in item when it doesnt exist, which breaks execution. The if test is safe, and else it just dumps the item.

**Comment by skilion** [comment] 2017-06-16 09:55
The `name` key should always be present in the JSON of an item. I am closing this issue assuming the error was caused by a dysfunction of OneDrive itself

**Closed by skilion** 2017-06-16 09:55 UTC
