### ISSUE TITLE
onedrive.service fails after running for a while

### ISSUE THREAD

**Issue by eduracosta** [skilion/onedrive#260] opened 2017-11-28 17:33 UTC
I have installed onedrive and run it as a service using systemd as explained in your instructions. After it runs for a while I get this failure:

Nov 28 18:46:00 lenedu onedrive[28301]: src/onedrive.d:302 void onedrive.OneDriveApi.download(const(char)[], immutable(char)[]) [0x57937b]
Nov 28 18:46:00 lenedu onedrive[28301]: src/onedrive.d:135 void onedrive.OneDriveApi.downloadById(const(char)[], immutable(char)[]) [0x577315]
Nov 28 18:46:00 lenedu onedrive[28301]: src/sync.d:288 void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x585143]
Nov 28 18:46:00 lenedu onedrive[28301]: src/sync.d:259 void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x584b7d]
Nov 28 18:46:00 lenedu onedrive[28301]: src/sync.d:169 void sync.SyncEngine.applyDifferences() [0x583bf9]
Nov 28 18:46:00 lenedu onedrive[28301]: src/main.d:184 void main.performSync(sync.SyncEngine) [0x56fceb]
Nov 28 18:46:00 lenedu onedrive[28301]: src/main.d:114 _Dmain [0x56f513]
Nov 28 18:46:00 lenedu systemd[32368]: onedrive.service: Main process exited, code=exited, status=1/FAILURE
Nov 28 18:46:00 lenedu systemd[32368]: onedrive.service: Unit entered failed state.
Nov 28 18:46:00 lenedu systemd[32368]: onedrive.service: Failed with result 'exit-code'.

After I restart the service it continues running fine until the next failure.

**Comment by eduracosta** [comment] 2017-11-28 19:15
It happened again, and this time I was able to get more info from the logs

Nov 28 20:32:50 lenedu onedrive[1151]: Downloading: Documents/My Projects/c# samples/vtk/C#/WpfVTK/bin/Debug/WpfVTK.vshost.exe.manifest
Nov 28 20:32:52 lenedu onedrive[1151]: Downloading: Documents/My Projects/c# samples/vtk example/packages/Activiz.NET.x64.5.8.0/lib/net20/Kitware.VTK.xml
Nov 28 20:36:05 lenedu onedrive[1151]: std.net.curl.CurlException@std/net/curl.d(4343): Failure when receiving data from the peer on handle 134E4F0
Nov 28 20:36:05 lenedu onedrive[1151]: ----------------
Nov 28 20:36:05 lenedu onedrive[1151]: ??:? pure @safe void std.exception.bailOut!(std.net.curl.CurlException).bailOut(immutable(char)[], ulong, const(char[])) [0x603314]
Nov 28 20:36:05 lenedu onedrive[1151]: ??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x603289]
Nov 28 20:36:05 lenedu onedrive[1151]: ??:? void std.net.curl.Curl._check(int) [0x5dca1c]
Nov 28 20:36:05 lenedu onedrive[1151]: ??:? int std.net.curl.Curl.perform(std.typecons.Flag!("throwOnError").Flag) [0x5dce50]
Nov 28 20:36:05 lenedu onedrive[1151]: ??:? int std.net.curl.HTTP.perform(std.typecons.Flag!("throwOnError").Flag) [0x5d9a3c]
Nov 28 20:36:05 lenedu onedrive[1151]: src/onedrive.d:302 void onedrive.OneDriveApi.download(const(char)[], immutable(char)[]) [0x57937b]
Nov 28 20:36:05 lenedu onedrive[1151]: src/onedrive.d:135 void onedrive.OneDriveApi.downloadById(const(char)[], immutable(char)[]) [0x577315]
Nov 28 20:36:05 lenedu onedrive[1151]: src/sync.d:288 void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x585143]
Nov 28 20:36:05 lenedu onedrive[1151]: src/sync.d:259 void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x584b7d]
Nov 28 20:36:05 lenedu onedrive[1151]: src/sync.d:169 void sync.SyncEngine.applyDifferences() [0x583bf9]
Nov 28 20:36:05 lenedu onedrive[1151]: src/main.d:184 void main.performSync(sync.SyncEngine) [0x56fceb]
Nov 28 20:36:05 lenedu onedrive[1151]: src/main.d:114 _Dmain [0x56f513]
Nov 28 20:36:05 lenedu systemd[1113]: onedrive.service: Main process exited, code=exited, status=1/FAILURE
Nov 28 20:36:05 lenedu systemd[1113]: onedrive.service: Unit entered failed state.
Nov 28 20:36:05 lenedu systemd[1113]: onedrive.service: Failed with result 'exit-code'.

**Comment by skilion** [comment] 2018-01-02 20:08
Duplicate of #11

**Closed by skilion** 2018-01-02 20:08 UTC
