### ISSUE TITLE
onedrive.d(408): HTTP request returned status code 504 (Gateway Timeout)

### ISSUE THREAD

**Issue by eakbas** [skilion/onedrive#320] opened 2018-03-21 08:20 UTC
I am using `onedrive v1.1.1` on Ubuntu 16.04. When I run onedrive with `--verbose`, I get the error below.  

```
onedrive.OneDriveException@src/onedrive.d(408): HTTP request returned status code 504 (Gateway Timeout)
{
    "error": {
        "code": "UnknownError",
        "innerError": {
            "date": "2018-03-21T08:16:10",
            "request-id": "f410ecf7-6c03-41ab-89dd-0d67d41a88cf"
        },
        "message": ""
    }
}
----------------
src/onedrive.d:33 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x571ef0]
src/onedrive.d:352 std.json.JSONValue onedrive.OneDriveApi.upload(immutable(char)[], immutable(char)[]) [0x5718a9]
src/onedrive.d:147 std.json.JSONValue onedrive.OneDriveApi.simpleUpload(immutable(char)[], immutable(char)[], immutable(char)[], immutable(char)[], const(char)[]) [0x570736]
src/sync.d:616 void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x57b491]
src/sync.d:591 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x57b0b4]
src/sync.d:586 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x57afd7]
src/sync.d:586 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x57afd7]
src/sync.d:586 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x57afd7]
src/sync.d:586 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x57afd7]
src/sync.d:586 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x57afd7]
src/sync.d:586 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x57afd7]
src/sync.d:586 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x57afd7]
src/sync.d:442 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x57a433]
src/main.d:192 void main.performSync(sync.SyncEngine) [0x5691f3]
src/main.d:118 _Dmain [0x568d24]
```

**Comment by eakbas** [comment] 2018-04-20 06:39
Thanks for the reply. 

Running `onedrive` or `onedrive --verbose --debug-https` doesn't give any errors but it does not sync. 

Then, when I try `onedrive --resync` it gives the following error: 

```
core.exception.AssertError@src/itemdb.d(293): Assertion failure
----------------
??:? _d_assertp [0x5aa755]
src/itemdb.d:293 immutable(char)[] itemdb.ItemDatabase.computePath(const(char)[], const(char)[]) [0x57e450]
src/sync.d:364 void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0x5994d2]
src/sync.d:303 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x599170]
src/sync.d:167 void sync.SyncEngine.applyDifferences() [0x5989dd]
src/main.d:313 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x581536]
src/main.d:206 _Dmain [0x580f20]
```

**Comment by abraunegg** [comment] 2018-04-20 06:44
In #314 you need to use --synchronize to get it to sync - this is a change in behavior so that running onedrive by itself with no flags it doesn't sync - preventing any accidental running.

Did you remove the `~/.config/onedrive/items.sqlite3` before attempting a sync?

**Comment by eakbas** [comment] 2018-04-20 06:52
I removed `~/.config/onedrive/items.sqlite3` and then did `sudo onedrive --synchronize --verbose --debug-https` (BTW, I need to put `sudo`, otherwise it complains about not being able to open the lof file under `/var/log/onedrive/`), I get the same error: 

```
core.exception.AssertError@src/itemdb.d(293): Assertion failure
----------------
??:? _d_assertp [0x5aa755]
src/itemdb.d:293 immutable(char)[] itemdb.ItemDatabase.computePath(const(char)[], const(char)[]) [0x57e450]
src/sync.d:364 void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0x5994d2]
src/sync.d:303 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x599170]
src/sync.d:167 void sync.SyncEngine.applyDifferences() [0x5989dd]
src/main.d:313 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x581536]
src/main.d:206 _Dmain [0x580f20]
```

**Comment by garther** [comment] 2018-04-20 08:06
Hi, I have the same issue with onedrive. Using master branch everything works until I restart my laptop, then error 500 occurs. With ver 314 I am getting:

`marcin@marcin-T470s-lnx:~/projects/git/onedrive$ onedrive --synchronize --verbose 
Loading config ...
Using Config Dir: /home/marcin/.config/onedrive
No config file found, using defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/marcin/OneDrive
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: 
Default Root ID: 
Remaining Free Space: 1099170626235
Applying changes of Path ID: 
core.exception.AssertError@src/itemdb.d(293): Assertion failure
----------------
??:? _d_assert [0x73e4c555]
??:? [0xfafe15b0]
??:? [0xfafdef03]
??:? [0xfafdda2c]
??:? [0xfaff058c]
??:? [0xfafef4a3]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x73e70c2f]
??:? _d_run_main [0x73e70afb]
??:? __libc_start_main [0x735cfb96]
??:? [0xfafd0a79]`

**Comment by abraunegg** [comment] 2018-04-20 08:10
I have found the DB assertion issue .. fixing at the moment

**Comment by abraunegg** [comment] 2018-04-20 08:45
Commit 66d00c5ec9e00b57e1e237477e9e12c80d46763c should fix the assertion issue.

**Comment by garther** [comment] 2018-04-20 08:53
Looks like it is wokring. Will test if error 500 comes back...
Thanks a lot @abraunegg ;)

**Comment by abraunegg** [comment] 2018-04-23 09:46
@eakbas @garther 

If you can get the latest commit for #314 - dff245d29bf09c979d5bc40e82b852b48c957ac5 that would be great.

Also if all working, can we close this issue?

**Comment by eakbas** [comment] 2018-04-24 06:06
Unfortunately, I've got an error. I'm running it again with `--verbose --debug-https`. Will report back.

**Comment by eakbas** [comment] 2018-04-24 08:36
Here is the error I get: 

```
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 504 Gateway Timeout
< Cache-Control: private
< Transfer-Encoding: chunked
< Content-Type: application/json
< request-id: e28960b0-ab78-4b01-adca-d95b342d1eda
< client-request-id: e28960b0-ab78-4b01-adca-d95b342d1eda
< x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceA","Ring":"5","ScaleUnit":"001","Host":"AGSFE_IN_5","ADSiteName":"AMS"}}
< Duration: 10130.383
< Strict-Transport-Security: max-age=31536000
< Date: Tue, 24 Apr 2018 06:33:15 GMT
< 
* Connection #1 to host graph.microsoft.com left intact
onedrive.OneDriveException@src/onedrive.d(538): HTTP request returned status code 504 (Gateway Timeout)
{
    "error": {
        "code": "UnknownError",
        "innerError": {
            "date": "2018-04-24T06:33:16",
            "request-id": "e28960b0-ab78-4b01-adca-d95b342d1eda"
        },
        "message": ""
    }
}
----------------
src/onedrive.d:33 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x5902bc]
src/onedrive.d:390 std.json.JSONValue onedrive.OneDriveApi.upload(immutable(char)[], immutable(char)[]) [0x58fac1]
src/onedrive.d:149 std.json.JSONValue onedrive.OneDriveApi.simpleUpload(immutable(char)[], immutable(char)[], immutable(char)[], immutable(char)[], const(char)[]) [0x58e6da]
src/sync.d:918 void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x59bfd6]
src/sync.d:764 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59b2e0]
src/sync.d:755 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59b1d7]
src/sync.d:755 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59b1d7]
src/sync.d:755 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59b1d7]
src/sync.d:755 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59b1d7]
src/sync.d:755 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59b1d7]
src/sync.d:755 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59b1d7]
src/sync.d:755 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59b1d7]
src/sync.d:755 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59b1d7]
src/sync.d:587 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x59a486]
src/main.d:315 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x58154f]
src/main.d:206 _Dmain [0x580f20]
```

**Comment by abraunegg** [comment] 2018-04-24 08:50
Is there a particular file / files / file quantity that your uploading that always triggers the issue?

My understanding on the error is that a system upstream to you (graph) is what is getting the time out from something else behind it. 

Will look at posting this to the OneDrive API team now that there is some more concrete log

**Comment by garther** [comment] 2018-04-24 11:34
I have no errors in the onedrive process but the files are not synced. Sometimes it downloads only directory tree but only top level and all of them are empty inside. Pushing to onedrive seems to be working...
```
2018-Apr-24 13:30:31.6499206 Creating directory Attachments
2018-Apr-24 13:30:31.6618887 Creating directory B
2018-Apr-24 13:30:31.6707607 Creating directory Backup
2018-Apr-24 13:30:31.6790525 Creating directory Backups
2018-Apr-24 13:30:31.6875399 Creating directory Calculators
2018-Apr-24 13:30:31.6960558 Creating directory Documents
2018-Apr-24 13:30:31.7044998 Creating directory IT Common
2018-Apr-24 13:30:31.7129878 Creating directory Legacy
2018-Apr-24 13:30:31.7215337 Creating directory Notes
2018-Apr-24 13:30:31.73017 Creating directory Scripts
2018-Apr-24 13:30:31.738546 Creating directory SSH
2018-Apr-24 13:30:31.7471188 Creating directory SSL
2018-Apr-24 13:30:31.7564707 Creating directory tmp
2018-Apr-24 13:30:31.7654258 Creating directory WIP
2018-Apr-24 13:30:31.7740468 Creating directory Work time
```
```
find .
.
./tmp
./SSL
./WIP
./Backup
./B
./Work time
./Calculators
./Backups
./Legacy
./SSH
./Scripts
./Notes
./IT Common
./Attachments
./Documents
```

**Comment by eakbas** [comment] 2018-04-24 17:54
@abraunegg 

> Is there a particular file / files / file quantity that your uploading that always triggers the issue?

This is hard to detect for me but will try to look at it.

**Comment by abraunegg** [comment] 2018-04-24 19:40
@garther 

Can you post a full debug log using `--debug-https` ?

**Comment by abraunegg** [comment] 2018-04-25 07:35
Does the onedrive application always fail on this file?

There is nothing wrong with the filename, nor the total path length (130 characters). Maybe there is something within the file that OneDrive at the backend is having an issue with .. hence the 504 error.

If fails always on this file - it would also give them a reproducer to assist in fixing.

**Comment by garther** [comment] 2018-04-25 07:40
@abraunegg - here is the log.
[onedrive_debug.log](https://github.com/skilion/onedrive/files/1945925/onedrive_debug.log)

**Comment by abraunegg** [comment] 2018-04-25 08:04
@garther 

Can you download the latest codebase & rebuild your client?

Option 1:
```
git clone https://github.com/skilion/onedrive.git
git fetch origin pull/314/head:pr314
git checkout pr314
make
make install
```

Option 2:

```
git clone https://github.com/abraunegg/onedrive.git
make
make install
```

Checking your logfile - you are running some parts which I reverted which were causing issues which have since been rectified.

**Comment by eakbas** [comment] 2018-04-25 15:04
@abraunegg The file I mentioned does not exist in my local folder! But it does on OneDrive. I don't know what's wrong. 

After deleting this file in my local folder and re-running onedrive, I get a different error on another file. Log is attached. 
[error.log](https://github.com/skilion/onedrive/files/1947585/error.log)

And, why do I have to run #314 with `sudo`? It messed up the permissions (changed owner to root) of some of my files.

**Comment by abraunegg** [comment] 2018-04-25 18:57
@eakbas 

Can we do a webex?

**Comment by eakbas** [comment] 2018-04-26 06:30
@abraunegg Sure. I don't know how to do a webex. Maybe you sent me an email first? You can reach my webpage through my github profile. Thanks.

**Comment by abraunegg** [comment] 2018-04-26 09:29
@garther 

Any update from your side?

**Comment by garther** [comment] 2018-04-26 09:39
It seems to be working now, will let you know after some more tests.

**Comment by abraunegg** [comment] 2018-04-27 21:41
@garther 

Any further update after further testing?

@eakbas 

Any update from your side?

**Comment by abraunegg** [comment] 2018-04-29 03:45
@eakbas 
Any update?

**Comment by eakbas** [comment] 2018-04-30 05:46
@abraunegg 

Previously, I was using the changes in #314 but now I tried https://github.com/abraunegg/onedrive.git and did everything from scratch. I ran `onedrive --synchronize --local-first --verbose` (I no longer have the `sudo` problem) and I got: 

```
Uploading file ./[...I deleted this part...]/teaching/232-20172/slides/week07_sequential_circuit_design_examples_and_state_reduction.pptx...onedrive.OneDriveException@src/onedrive.d(540): HTTP request returned status code 504 (Gateway Timeout)
{
    "error": {
        "code": "UnknownError",
        "innerError": {
            "date": "2018-04-28T13:34:33",
            "request-id": "a9617c4f-31ea-49bb-9943-d7a0e5732448"
        },
        "message": ""
    }
}
----------------
src/onedrive.d:33 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x59145c]
src/onedrive.d:392 std.json.JSONValue onedrive.OneDriveApi.upload(immutable(char)[], immutable(char)[]) [0x590c61]
src/onedrive.d:138 std.json.JSONValue onedrive.OneDriveApi.simpleUpload(immutable(char)[], immutable(char)[], immutable(char)[], immutable(char)[], const(char)[]) [0x58f7c2]
src/sync.d:923 void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x59d216]
src/sync.d:808 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59c900]
src/sync.d:799 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59c7f7]
src/sync.d:799 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59c7f7]
src/sync.d:799 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59c7f7]
src/sync.d:799 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59c7f7]
src/sync.d:799 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x59c7f7]
src/sync.d:631 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x59baa5]
src/main.d:328 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x5826ff]
src/main.d:219 _Dmain [0x5820cf]
```

Next, I'm running the following to see if I will get the same error: 

```
rm ~/.config/onedrive/items.*
onedrive --synchronize --local-first --verbose 
```

**Comment by eakbas** [comment] 2018-04-30 06:26
This time, I got the same error on a different file: 

```
Uploading file [...I deleted this part...]/teaching/archive/20162_232/slides/week02-03-Combinational_Logic-v1-emre-desktop.pptx...onedrive.OneDriveException@src/onedrive.d(540): HTTP request returned status code 504 (Gateway Timeout)
{
    "error": {
        "code": "UnknownError",
        "innerError": {
            "date": "2018-04-30T05:58:38",
            "request-id": "bc9360fa-9c21-488a-83d5-c38c2eefb361"
        },
        "message": ""
    }
}
----------------
src/onedrive.d:33 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x59145c]
src/onedrive.d:392 std.json.JSONValue onedrive.OneDriveApi.upload(immutable(char)[], immutable(char)[]) [0x590c61]
src/onedrive.d:147 std.json.JSONValue onedrive.OneDriveApi.simpleUploadReplace(immutable(char)[], immutable(char)[], immutable(char)[], const(char)[]) [0x58f8fa]
src/sync.d:731 void sync.SyncEngine.uploadFileDifferences(itemdb.Item, immutable(char)[]) [0x59c2d0]
src/sync.d:662 void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x59bc39]
src/sync.d:682 void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0x59bdf9]
src/sync.d:659 void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x59bc06]
src/sync.d:682 void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0x59bdf9]
src/sync.d:659 void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x59bc06]
src/sync.d:682 void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0x59bdf9]
src/sync.d:659 void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x59bc06]
src/sync.d:682 void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0x59bdf9]
src/sync.d:659 void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x59bc06]
src/sync.d:682 void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0x59bdf9]
src/sync.d:659 void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x59bc06]
src/sync.d:682 void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0x59bdf9]
src/sync.d:659 void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x59bc06]
src/sync.d:628 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x59ba61]
src/main.d:328 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x5826ff]
src/main.d:219 _Dmain [0x5820cf]
```

**Comment by abraunegg** [comment] 2018-04-30 08:54
@eakbas 

Thanks - it appears you get the 504 error only with .pptx files. I am wondering if there is something 'unique' in those files that OneDrive (after uploading the file) has trouble with processing / parsing / interpreting the metadata.

**Comment by abraunegg** [comment] 2018-04-30 09:38
Submitted this under the OneDrive API team for investigation:

https://github.com/OneDrive/onedrive-api-docs/issues/848

**Comment by FlorisRemmen** [comment] 2018-05-02 11:34
@abraunegg I am facing a similar issue. 

Did make uninstall and clone from your github. Removed the sqlite file and rerun with synchronize. 

Reproducable 100%. If the error is only with .pptx files, I can try to add .pptx to my exclude list in the config file? 

```
< HTTP/1.1 504 Gateway Timeout
< Cache-Control: private
< Transfer-Encoding: chunked
< Content-Type: application/json
< request-id: 7633c25f-bbd0-470a-a89c-4d06b4399bdb
< client-request-id: 7633c25f-bbd0-470a-a89c-4d06b4399bdb
< x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceA","Ring":"5","ScaleUnit":"001","Host":"AGSFE_IN_31","ADSiteName":"AMS"}}
< Duration: 20002.8389
< Strict-Transport-Security: max-age=31536000
< Date: Wed, 02 May 2018 10:01:13 GMT
< 
* Connection #1 to host graph.microsoft.com left intact
onedrive.OneDriveException@src/onedrive.d(540): HTTP request returned status code 504 (Gateway Timeout)
{
    "error": {
        "code": "UnknownError",
        "innerError": {
            "date": "2018-05-02T10:01:13",
            "request-id": "7633c25f-bbd0-470a-a89c-4d06b4399bdb"
        },
        "message": ""
    }
}
----------------
src/onedrive.d:33 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x592394]
src/onedrive.d:312 std.json.JSONValue onedrive.OneDriveApi.get(const(char)[], bool) [0x5917b3]
src/onedrive.d:115 std.json.JSONValue onedrive.OneDriveApi.viewChangesById(const(char)[], const(char)[], const(char)[]) [0x590479]
src/sync.d:323 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x59b224]
src/sync.d:184 void sync.SyncEngine.applyDifferences() [0x59aacd]
src/main.d:326 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x58361e]
src/main.d:219 _Dmain [0x583007]
```

PS: I had already made a post about the service error earlier (dont remember ref number) and this was indeed resolved in your #314 .

Thanks in advance

**Comment by abraunegg** [comment] 2018-05-02 20:49
Can you confirm that it failed on a pptx file? If you can check the logs & share the pptx file (if not sensitive) then we can add that to the reproducer steps on the OneDrive API site so that the issue can be fixed.

**Comment by abraunegg** [comment] 2018-05-03 09:54
@eakbas @FlorisRemmen 
Can you tell me the file size of the .pptx items, and if possible provide them to me via email for testing?

**Comment by eakbas** [comment] 2018-05-03 10:44
My pptx is 2.5MB. I sent it to you via email.

**Comment by abraunegg** [comment] 2018-05-03 20:53
Thanks - so the file size is smaller than the current threshold to perform a session upload.

When I upload that same file here, there are no issues however:
```
Uploading new items of 564dfa8a-bd52-969a-f4c6-38488860d952
OneDrive Client requested to create remote path: 564dfa8a-bd52-969a-f4c6-38488860d952/pictures/eakbas
The requested directory to create was not found on OneDrive - creating remote directory: 564dfa8a-bd52-969a-f4c6-38488860d952/pictures/eakbas
Sucessfully created the remote directory 564dfa8a-bd52-969a-f4c6-38488860d952/pictures/eakbas on OneDrive
Uploading file 564dfa8a-bd52-969a-f4c6-38488860d952/pictures/eakbas/week02-03-Combinational_Logic-v1.pptx... done.
Remaining free space: 112547922966
```

What I will do is look at adding in some additional logic to handle a 504 response similar to how a 412 is being handled to retry.

**Comment by abraunegg** [comment] 2018-05-03 21:31
@eakbas @FlorisRemmen 
The other interesting aspect is that both of you experience this issue in the following MS DC:

```
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceA","Ring":"5","ScaleUnit":"001","Host":"AGSFE_IN_31","ADSiteName":"AMS"}}
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceA","Ring":"4","ScaleUnit":"000","Host":"AGSFE_IN_3","ADSiteName":"AMS"}}
```

Perhaps something really localised in that DC ..

**Comment by abraunegg** [comment] 2018-05-03 22:02
@eakbas @FlorisRemmen 

Before I commit this patch - can you please test this patch locally:
```
+++ onedrive.modified/src/sync.d        2018-05-04 07:43:04.000000000 +1000
@@ -327,9 +327,13 @@
                                        log.vlog("Delta link expired, resyncing...");
                                        deltaLink = null;
                                        continue;
-                               } else {
-                                       throw e;
+                               } 
+                               if (e.httpStatusCode == 504) {
+                                       // HTTP request returned status code 504 (Gateway Timeout)
+                                       // Retry
+                                       changes = onedrive.viewChangesById(driveId, defaultRootId, deltaLink);
                                }
+                               else throw e;
                        }
                        foreach (item; changes["value"].array) {
                                bool isRoot = false;
@@ -751,7 +755,16 @@
                                                write("Uploading file ", path, "...");
                                                JSONValue response;
                                                if (getSize(path) <= thresholdFileSize) {
-                                                       response = onedrive.simpleUploadReplace(path, item.driveId, item.id, item.eTag);
+                                                       try {
+                                                               response = onedrive.simpleUploadReplace(path, item.driveId, item.id, item.eTag);
+                                                       } catch (OneDriveException e) {
+                                                               if (e.httpStatusCode == 504) {
+                                                                       // HTTP request returned status code 504 (Gateway Timeout)
+                                                                       // Try upload as a session
+                                                                       response = session.upload(path, item.driveId, item.parentId, baseName(path), eTag);
+                                                               }
+                                                               else throw e;
+                                                       }
                                                        writeln(" done.");
                                                } else {
                                                        writeln("");
@@ -943,7 +956,16 @@
                                        write("Uploading file ", path, "...");
                                        JSONValue response;
                                        if (getSize(path) <= thresholdFileSize) {
-                                               response = onedrive.simpleUpload(path, parent.driveId, parent.id, baseName(path));
+                                               try {
+                                                               response = onedrive.simpleUpload(path, parent.driveId, parent.id, baseName(path));
+                                                       } catch (OneDriveException e) {
+                                                               if (e.httpStatusCode == 504) {
+                                                                       // HTTP request returned status code 504 (Gateway Timeout)
+                                                                       // Try upload as a session
+                                                                       response = session.upload(path, parent.driveId, parent.id, baseName(path));
+                                                               }
+                                                               else throw e;
+                                                       }
                                                writeln(" done.");
                                        } else {
                                                writeln("");
```

As I cannot reproduce the 504 error here with your pptx files, and you can reproduce consistently - it would be great if you can apply this locally and report back.

**Comment by FlorisRemmen** [comment] 2018-05-04 08:56
Hi

Yesterday I faced some trouble with my pc so I had to reinstall ubuntu. I am now running 18.04 and haven't had the time to set up onedrive yet. Will report back next week when I install. 

I can't confirm it was a pptx.

**Comment by eakbas** [comment] 2018-05-04 12:08
@abraunegg I applied the patch you sent, removed `items.*` and did `onedrive --synchronize --local-first --verbose`. This time I got an error at another file (not a pptx file): 

```
Skipping item - excluded by skip_file config: ./[...deleted...]_BACKUP/.lesshst
Applying changes of Path ID: 01DDBXS2F6Y2GOVW7725BZO354PWSELRRZ
HTTP request returned status code 500 (Internal Server Error)
{
    "error": {
        "code": "InternalServerError",
        "innerError": {
            "date": "2018-05-04T12:00:32",
            "request-id": "d8a681f2-0936-4a6b-ae7b-d102ae48079d"
        },
        "message": "nextLink value without skip or skiptoken"
    }
}
Applying changes of Path ID: 01DDBXS2F6Y2GOVW7725BZO354PWSELRRZ
HTTP request returned status code 500 (Internal Server Error)
{
    "error": {
        "code": "InternalServerError",
        "innerError": {
            "date": "2018-05-04T12:00:33",
            "request-id": "dfca849b-275d-45e9-8a07-d99bdc81f350"
        },
        "message": "nextLink value without skip or skiptoken"
    }
}
Applying changes of Path ID: 01DDBXS2F6Y2GOVW7725BZO354PWSELRRZ
onedrive.OneDriveException@src/onedrive.d(540): HTTP request returned status code 500 (Internal Server Error)
{
    "error": {
        "code": "InternalServerError",
        "innerError": {
            "date": "2018-05-04T12:00:35",
            "request-id": "478b2daf-779a-478a-9075-d605f421fe59"
        },
        "message": "nextLink value without skip or skiptoken"
    }
}
----------------
src/onedrive.d:33 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x59145c]
src/onedrive.d:312 std.json.JSONValue onedrive.OneDriveApi.get(const(char)[], bool) [0x59087b]
src/onedrive.d:115 std.json.JSONValue onedrive.OneDriveApi.viewChangesById(const(char)[], const(char)[], const(char)[]) [0x58f541]
src/sync.d:323 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x59a2ea]
src/sync.d:184 void sync.SyncEngine.applyDifferences() [0x599b89]
src/main.d:326 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x5826e6]
src/main.d:219 _Dmain [0x5820cf]
```

**Comment by abraunegg** [comment] 2018-05-04 19:59
@eakbas 

OK - so the the original problem of the 504 error being returned when uploading a file does not exist.

Do you feel that the above patch has resolved your issue? Should I add in additional logging so that we know when this event has occurred?

Regarding this new error:

```
onedrive.OneDriveException@src/onedrive.d(540): HTTP request returned status code 500 (Internal Server Error)
{
    "error": {
        "code": "InternalServerError",
        "innerError": {
            "date": "2018-05-04T12:00:35",
            "request-id": "478b2daf-779a-478a-9075-d605f421fe59"
        },
        "message": "nextLink value without skip or skiptoken"
    }
}
```
This error is caused by 'large volume changes' occuring on the OneDrive Web Interface (delete a folder, move a folder etc). This is actually a OneDrive API error (confirmed bug) that I cannot resolve:

OneDrive/onedrive-api-docs#848

If you remove the items database file does the client continue to sync and process the changes?

**Comment by abraunegg** [comment] 2018-05-05 06:47
So with the latest commit - when a 500 error is returned, the following will be displayed:
```
OneDrive returned a 'HTTP 500 - Internal Server Error'
This is a OneDrive API Bug - https://github.com/OneDrive/onedrive-api-docs/issues/844
```
Then the application will gracefully exit. This IMHO is better than 'onedrive' crashing out.

**Comment by abraunegg** [comment] 2018-05-05 21:02
OK - great .. if resolved then, can we close this issue?

**Comment by eakbas** [comment] 2018-05-06 05:42
I guess so.

**Closed** 2018-05-06 05:43 UTC
